### ISSUE TITLE
Downcase email before validations

### ISSUE THREAD

**Issue by ankane** [plataformatec/devise#1005]
Getting an ActiveRecord::RecordNotUnique error when I do this.

```
User.create(:email => "mIxEdCaSe@test.com", :password => "test123")
User.create(:email => "mIxEdCaSe@test.com", :password => "test123") # throws exception
```

Instead, validation should fail the second time.

**Quick fix** On line 25 of lib/devise/models/database_authenticatable.rb, this line

```
before_save :downcase_keys
```

should be replaced with

```
before_validation :downcase_keys
```

**Comment by dla-c-box** [comment]
Note: this fix (replacing `before_save` with `before_validation`) prevents the downcasing of the email to be done when we skip the validation (and explains why we have duplicate emails in a DB, e.g. "User@test.com" and "user@test.com")
e.g.
- user.save! <-- the email is downcased
- user.save(validate: false) <-- the email is **not** downcased
- user.update_attribute(:email, "UPPERCASE@test.com") <-- the email is **not** downcased (because update_attribute [skips validation](https://apidock.com/rails/ActiveRecord/Persistence/update_attribute))
