### ISSUE TITLE
ActiveRecord::RecordNotUnique on create and update with existing email

### ISSUE THREAD

**Issue by sush** [plataformatec/devise#1356]
Hi,

I have upgraded to rails 3.1 and I encounter an error when I try to create (or update) a user with an existing email (I want email to be unique).

I get this error with PostgreSQL :

`ActiveRecord::RecordNotUnique in Devise::RegistrationsController#create`
`PGError: ERROR:  duplicate key value violates unique constraint "index_users_on_email"`

I do use :validatable in my User model (the presence and regexp validates work) and I also tried to remove it and implement all the validations in my User model but I get the same error.

**Comment by allenlsy** [comment]
I encountered this problem recently. I'm using Rails 4.2.1, Devise 3.4.1

Here is the server log:

```
ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry 'xxx@yahoo.co.id' for key 'index_users_on_email': INSERT INTO `users` ...

app/controllers/api/registrations_controller.rb ? in create_wo_oauth (application)
       if @user.save
```

I doubt that it was because a user click on register twice too quick, so when the 2nd POST request arrived at the server, the 1st request was not finished, so the 2nd passes the Rails uniqueness validation. Then the 1st request finishes, user was created. The 2nd request hits the DB, and caused this problem.

@josevalim Is this possible?

**Comment by AmitPatel-BoTreeConsulting** [comment]
I am getting same error with Rails 4.2.3 and Devise 3.5.1. I am using omniauth with Devise and trying to signup using twitter.

**Comment by acandael** [comment]
I am also encountering this issue:

PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_email"

The odd thing is that I myself can login with CAS, but anyone else in my organisation trying to log in gets the above error.

My version of rails is 4.2.2
the version of devise is: 3.5.2
