### ISSUE TITLE
replace webrat with capybara in integration tests

### ISSUE THREAD

**Issue by nashby** [plataformatec/devise#1465]
Well, what do you think? Is it reasonable?
If it is I can do it.

**Comment by feliperenan** [comment]
Maybe, now we can migrate our integration tests to capybara. I'm reopening this issue to keep it on our way.

**Comment by feliperenan** [comment]
I've spent time trying to migrate those tests from Webrat to Capybara but I realized that it requires a lot of changes since we're going to refactor several tests and If we do that, we need do it carefully to not leave some scenario uncovered.

By now, I'm going to close this issue since @tegon and I started working on this because we had some warnings coming from Webrat. But it is solved on this PR: https://github.com/plataformatec/devise/pull/5018
