### ISSUE TITLE
can't override views

### ISSUE THREAD

**Issue by bl4d3** [plataformatec/devise#1824]
Hi,
I'm using 
ruby 1.8.7 (2008-08-11 patchlevel 72) [i486-linux] 
rails 3.1.0
on a VPS and I can't update the ruby versione, I have a problem with devise 2.0.4 when I try to override the views.
In my app I have
app/views/devise/{all the views generated by rails generate devise:views}
but they are not loaded in my app even if in the log i see

Rendered devise/registrations/new.html.erb within layouts/frontend (7.9ms)

maybe it going to catch the erb into the devise gem, it is just a guess...

**Comment by joshleblanc** [comment]
Just in case someone runs into this again, I had this problem on windows due to paths being case insensitive.

Running `rails s` in `C:\users\horiz\rubymineprojects\scout` caused devise to render views from the gem. The *actual* path is `C:\Users\horiz\RubymineProjects\scout`. Changing to this directory and running the server again caused everything work correctly.
