### ISSUE TITLE
When updating your user password, you aren't required to enter a password confirmation

### ISSUE THREAD

**Issue by ryanbooker** [plataformatec/devise#228]
- Edit a user
- Enter a new password
- DO NOT enter a password confirmation
- Enter the old password
- Press Update

EXPECTED: Password confirmation error
ACTUAL: Password change succeeds

If you DO enter a password confirmation the check is done as expected and it must agree.

**Comment by jjb** [comment]
hello from 15 years in the future

i experienced the bug where chrome or maybe another extension autofills current password and for some reason "fills" thew newpassword and new password confirmation fields with a blank string, equivalent of adding `value=""` to the field using chrome inspector. those values make it all the way to `def update_with_password` which then clears them

```ruby
        if params[:password].blank?
          params.delete(:password)
          params.delete(:password_confirmation) if params[:password_confirmation].blank?
        end
```

and continues the NOOP update.

the user can accidentally submit a blank form and get a disconcerting success message, and they might be concerned they set their password to a blank string.

i solved it in my app by adding `required` to the html of the form

i'm not sure what a more thorough backend solution would be- i don't know if it's solvable in a generic way in Devise::RegistrationsController#update, because we would have to know that the intent is to update the password - assume that's the case if the two password params are present? and then disallow blank ones... do we do any other validation or just disallow blank ones? should we actually disallow blank ones in `def update_with_password`?
