### ISSUE TITLE
Upgrading to Devise v3 invalidates all sessions

### ISSUE THREAD

**Issue by moll** [plataformatec/devise#2596]
Just discovered Devise v3 (or it could be the Warden it uses) invalidates all database backed sessions because it changes the signature of `warden.user.account.key` it keeps in the session's `data` attribute. I don't see this mentioned in the CHANGELOG.

**Comment by javiercr** [comment]
Sorry for re-opening this issue, but I'm trying to update an app from devise 2.1.2 to 3.4.1 and came across the note in the changelog for 2.2.4:

> Changes on session storage will expire all existing sessions on upgrade. For those storing the session in the DB, they can be upgraded according to this gist: https://gist.github.com/moll/6417606

However, on my local testings, sessions are working fine. I am worried this could be different when I deploy to production. Do you know if that behavior from 2.2.4 has been fixed recently in a newer version, and that's why I am not seeing the session invalidation'

Thanks.

**Comment by moll** [comment]
Check the format of the data in the database. Is it still in the old style?

**Comment by javiercr** [comment]
Thank you for your reply @moll. Note I am using Rails 3.2 with Marshal serializer, not the JSON one. Here is the format:
```
{
"_csrf_token"=>"XXXXX", "warden.user.user.key"=>["User", [12345], "XXXXXXX"]}
```

**Comment by moll** [comment]
According to my migration script it's already in the new form. Perhaps you had another cookie that signed you in. The remember me feature IIRC has a separate one.

**Comment by javiercr** [comment]
I finally deployed to production and sessions are fine without having to migrate them. I am not sure why is that, but I think that note on the changelog could be misleading for scenarios like mine (I almost decided to not upgrade when I saw that for the first time).

Thank you guys anyway!

**Comment by moll** [comment]
My bet's on your "remember-me" feature like I said above.
Plus I shared a migration script, so it's no big deal. ;)
