### ISSUE TITLE
Shouldn't Devise be triggering :authentication event with all sign_in calls?

### ISSUE THREAD

**Issue by leods92** [plataformatec/devise#2614]
Currently, SessionsController#create triggers Warden's :authentication event, thus its callbacks.
RegistrationsController#create and PasswordsController#update do not call that event but they allow users to authenticate, that is, set their user for the first time in a session.

That happens because sign_in itself won't trigger such event (it could though, by sending :event => :authentication). As SessionsController#create calls warden.authenticate! as well the :authentication event ends up being called what doesn't happen in other default controllers.

I'm not sure if there's a reason why only "manual signing in" triggers authentication event. From my perspective, it'd make sense to do it at each sign_in call.
Because of this current behaviour, there's no way to set a callback after user's first signing in.
Warden's after_set_user is called all the time, unlike after_authentication.
However, with current Devise's way of handling authentication event only signing in via SessionsController will call Warden's after_authentication callbacks.

I'm always unsure whether I made a mistake when I submit an issue to a well-maintained project like this, so if I missed something, I'm really sorry.

**Comment by JacobEvelyn** [comment]
@josevalim I completely agree with @leods92 here and I'm not sure why this was closed. We want to track when users log in, and found that by using the `after_authentication` hook we're missing some cases where a user logs in—for instance with a token—and then starts performing actions within our app.

As @leods92 mentioned, `after_set_user` doesn't work for us because that appears to be called on every request, and sometimes many times within a single request.

Does our use case make sense? Is there a better way we should be hooking into the login events?

**Comment by alexsumdog** [comment]
Just want to note that I'm having the same issue.

We'd like to execute some actions every time a user signs in, whether through normal username / password authentication or a manual call to Devise's `sign_in`, but there's no exposed hook (through either Devise or Warden) that allows us to catch both of these events.

@JacobEvelyn - I'd be interested to know if you found any neat way to deal with this!

**Comment by JacobEvelyn** [comment]
@alexsumdog I think we ended up just using `after_authentication` and deciding we were comfortable ignoring other sign-ins. Definitely not an ideal solution though!
