### ISSUE TITLE
Initial confirmation email not being sent

### ISSUE THREAD

**Issue by krsyoung** [plataformatec/devise#2688]
Per the documentation "Confirmation instructions are sent to the user email after creating a record and when manually requested by a new confirmation instruction request.".  However, in my deployment I'm currently not receiving the confirmation emails on initial user creation.  The manual request for a confirmation is working perfectly.

I am  unsure if it is some side effect of a configuration that I have. I am able to resolve the issue by adding the following code change to `send_confirmation_notification?` to consider the unconfirmed_email as the email value is initially blank:

``` ruby
# lib/devise/models/confirmable.rb
def send_confirmation_notification?
    confirmation_required? && !@skip_confirmation_notification && (!self.email.blank? || !self.unconfirmed_email.blank?)
end
```

I'm running with Devise 3.1.1 and have the following config settings related to confirmations:

``` ruby
# config/devise.rb
config.allow_unconfirmed_access_for = 0.days
config.confirm_within = 3.days
config.reconfirmable = true
```

Curious if anybody else is seeing this issue or comments / thoughts on the implications of the code change I have made?

Thanks!

**Comment by TaiwoAyanleye** [comment]
Same here, @lkol's "config.reconfirmable = false" did resolve this, wondering what the implication might be?

**Comment by waleedarshad** [comment]
Same issue. Is there anyone who is able resolve it?

**Comment by benmaher** [comment]
Same issue. I discovered it using devise_invitable and when sending a new invite I got the error:

`An SMTP To address is required to send a message. Set the message smtp_envelope_to, to, cc, or bcc address.`

After tracing through devise_invitable and devise, I was able to determine it was happening during `if save(:validate => false)` in the class instance method `invite!` in `lib/devise_invitable/model.rb`. After checking the callbacks I focused on the devise `before_update` callback `postpone_email_change_until_confirmation_and_regenerate_confirmation_token`.

By itself, this callback isn't an issue even with devise_invitable. As described by others, the problem occurs when another save happens during creation (within `after_create`, `after_save`, or `after_commit`). This will trigger the update flow and callbacks which leads to `postpone_email_change_until_confirmation_and_regenerate_confirmation_token`.

```ruby
        def postpone_email_change_until_confirmation_and_regenerate_confirmation_token
          @reconfirmation_required = true
          self.unconfirmed_email = self.email
          self.email = self.email_was
          self.confirmation_token = nil
          generate_confirmation_token
        end
```

At this point, `self.email = self.email_was` sets email to `""`. `self.email_was` is part of [ActiveModel::Dirty](http://api.rubyonrails.org/classes/ActiveModel/Dirty.html). Because the same model instance is being used, `self.email_was` returns `""` - because `email` did not have a previous value when the record was created. Devise is assuming that the change in email is due to an update and not because of the creation. This assumption plays out here as it relies upon `email_changed?` (also from ActiveModel::Dirty) and if this new email should be reconfirmed.

```ruby
        def postpone_email_change?
          postpone = self.class.reconfirmable && email_changed? && !@bypass_confirmation_postpone && self.email.present?
          @bypass_confirmation_postpone = false
          postpone
        end
```

---

The following user model code produces the issue. In this example, `sign_in_count` will be set 1 only if 0 and then saves.

```ruby
class User < ActiveRecord::Base
...

  after_save :reveal_issue

  def reveal_issue
    if self.sign_in_count == 0
      self.sign_in_count == 1
      self.save
    end
  end

```

You can then verify it in the console.

Create user and see that email is present in the `user` instance:
`user = User.new(email: "sim@ple.ton", password:"simpleton", password_confirmation: "simpleton")`

Save user: 
`user.save`

Check user and email is now `""`:
`user`

Check last user stored and email is present:
`User.last`

Obviously a trivial example, but I found the issue because I had an `after_save` that was updating the username to a default that had the user `id` as part of the username. This could only happen after the record was saved so I could use the assigned `id`.

---
The following solutions have been tested only so far that the model instance `email` is not set to `""`. I cannot confirm if these produce undesired behavior.

#### Solution 1
Use `skip_reconfirmation!` to bypass `postpone_email_change_until_confirmation_and_regenerate_confirmation_token` during this update. I prefer this.

```ruby
class User < ActiveRecord::Base
...

  after_save :reveal_issue

  def reveal_issue
    if self.sign_in_count == 0
      self.skip_reconfirmation!
      self.sign_in_count == 1
      self.save
    end
  end

```

#### Solution 2
Make the updates after creation only if confirmation has occurred. This only works for `after_save` and `after_commit`. `after_create` only fires once upon creation so it would never execute the code.

```ruby
class User < ActiveRecord::Base
...

  after_save :reveal_issue

  def reveal_issue
    if self.confirmed? && self.sign_in_count == 0
      self.sign_in_count == 1
      self.save
    end
  end

```

#### Solution 3
Force a record reload before making updates. This fulfills the devise assumption concerning the state of the instance though it is another database hit.

```ruby
class User < ActiveRecord::Base
...

  after_save :reveal_issue

  def reveal_issue
    self.reload
    if self.sign_in_count == 0
      self.sign_in_count == 1
      self.save
    end
  end

```

**Comment by gfauredumont** [comment]
Hi,

I have the same issue, that is not resolved by setting `config.reconfirmable = false`.
I can't help notice that this issue is closed though :(

**Comment by gfauredumont** [comment]
For now, I have a hugly workaround:
In my User model, I added this:

```ruby
class User < ActiveRecord::Base
  devise :confirmable

  after_create: force_mail_confirmation

  def force_mail_confirmation
    self.send_confirmation_instructions
  end
end
```

Works like a charm... except that I suspect a `skip_confirmation` call would work anymore :/

Any help is more than welcome

**Comment by CJBrew** [comment]
I'm having this issue too. And it's apparently because of DeviseTokenAuth, for me:

``` ruby
class User < ActiveRecord::Base
  devise :registerable, :confirmable, :database_authenticatable
  
  include DeviseTokenAuth::Concerns::User
end
```

**Comment by rbovi** [comment]
In case anyone is still experiencing this, I'd been having this issue for a while and was able to resolve by moving the "include DeviseTokenAuth::Concerns::User" above the devise declarations.
 
Like so:
`include DeviseTokenAuth::Concerns::User

  # Include default devise modules.
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :confirmable`

Hope this helps someone. I feel like the devise_token_auth install action places this in an odd spot if you've previously installed devise for standard auth.

**Comment by davidsilvasmith** [comment]
Wow, thanks to @krsyoung, @antho1404, and especially @benmaher

I spent at least two hours debugging this yesterday and wondering why in the world email was empty.

Thanks for the `self.skip_reconfirmation!`, worked like a charm!

**Comment by ethagnawl** [comment]
@CJBrew [The default behavior is explicitly disabled by DeviseTokenAuth.](https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/models/devise_token_auth/concerns/user.rb#L120-L124)

```
  # this must be done from the controller so that additional params
  # can be passed on from the client
  def send_confirmation_notification?
    false
  end
```

AFAICT, the "additional params" they're referring to is just `confirm_success_url`.

**Comment by asl331** [comment]
> I'm having this issue too. And it's apparently because of DeviseTokenAuth, for me:
> 
> ```ruby
> class User < ActiveRecord::Base
>   devise :registerable, :confirmable, :database_authenticatable # (minimal set)
> 
>   include DeviseTokenAuth::Concerns::User
> end
> ```
> 
> Removing the DeviseTokenAuth concerns solves this issue, as does placing it above the devise settings. However, I've currently not tested whether the tokens still work...
> 
> My fixed User class:
> 
> ```ruby
> class User < ActiveRecord::Base
>   include DeviseTokenAuth::Concerns::User
> 
>   devise :database_authenticatable, :registerable,
>          :recoverable, :rememberable, :trackable, :validatable,
>          :confirmable
> end
> ```

I'm using devise_token_auth along devise I spent 4 hours searching the solution and finally, this solves that issue thanks a lot @CJBrew

**Comment by kaka-ruto** [comment]
For those who face this problem whilst using Devise Token Auth, this one solved it for me

```
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :confirmable

  include DeviseTokenAuth::Concerns::User

  after_create :send_confirmation_email

  private

  def send_confirmation_email
    self.send_confirmation_instructions
  end
end
```
