### ISSUE TITLE
Sharing Devise on Multiple Engines

### ISSUE THREAD

**Issue by Bharat311** [plataformatec/devise#2827]
Hi, I have an application which has **multiple** rails engines mounted on it. Some of these engines use devise for authentication.

Now, it is easy to setup devise to work with one engine - by setting the **'router_name'** and **'parent_controller'** in _config/initializer/devise.rb_ file. But since, in this case, each DeviseController must inherit from each engine's own Application Controller and defining multiple devise initializer files simply overrides the values.

I think an optimum solution for this is to allow devise the ability to be able to mount to multiple engines. One way i propose for this is to have the devise provides **Mixins** for each controller and we should have a generator class that generates the controllers classes using those mixins and for each engine, which can be easily configured in the initializer file.

Another solution for this problem is to separate out all authentication to a single engine (and it can be configured to use devise easily), but that would require moving/copying of the layouts and js, css, etc. assets as well to that authentication engine, thus violating the DRY principle.

**Comment by chibicode** [comment]
> @josevalim, thanks for the quick response. In my application, we have several small apps that are using the same backend. The functionality of the sub-apps are mutually exclusive so we have separated them out to engines. And yes, we really want a different authentication end-point for each of them.

We have a similar problem...

**Comment by sudrao** [comment]
We have exactly the same requirement as @Bharat311! There are regular and admin users for the website and we have a separate engine for admins mounted in the main app. The mixin approach will work well for us.

**Comment by fmh** [comment]
@chibicode your wiki does not work as you can read in #4127

**Comment by mltsy** [comment]
I also find myself wishing this were possible. It has been very useful/promising to use Engines to organize mostly separate apps that all reference the same data, but I'm unable to do so, because Devise breaks in this use case.  I'm looking into alternate authentication for the Engine apps, but it sure would be much nicer to just use Devise for everything.

**Comment by tibomogul** [comment]
You can look at how Spree Commerce does it. It uses multiple engines, including one for devise  auth. It is easy to extend using more engines as extensions.

**Comment by mediafinger** [comment]
I am running into the same issue of having one modular Rails monolith with multiple engines - and multiple models like Admin and User that have different requirements for the authentication setup.

Is there by now a solution by Devise - which would allow to use the gem and not a fork or monkey-patches?

Or is this still unsolved and needs to be worked around?

**Comment by rickgorman** [comment]
Could this be addressed by allowing the `parent_controller` to be specified within the `devise_for` block in the routing layer, kind of like this:
```rb
devise_for :regular_user, parent_controller: "RegularUser::ApplicationController"
devise_for :admin_user, parent_controller: "AdminUser::ApplicationController"
```

Posting this because I ran into a similar issue when trying to set up two categories of users, albeit on the same monolith. The use case is a multi-sided marketplace where each category of user has a similar set of paths (i.e. "/", "/profile", "/foobar", etc) that each route to different controllers based on the type of user. This is important as an additional layer of security to prevent producers from seeing consumer's data and vice-versa.

I'm using `authenticate` blocks in `routes.rb` to differentiate routing between these two types of users like so:
```rb
authenticate :consumer_user do
  root "consumer_user/home#index"
end

authenticate :producer_user do
  root "producer_user/home#index
end
```

This works great, except that devise wants to inherit from its config's `parent_controller`, which is defined via an initializer:

https://github.com/heartcombo/devise/blob/ec0674523e7909579a5a008f16fb9fe0c3a71712/app/controllers/devise_controller.rb#L4

As a result, all devise controller inherit from `ApplicationController` and I had to add a bunch of methods in `ApplicationController` that deal with disambiguating between the different user categories, like this one for analytics:
```rb
class ApplicationController < ActionController::Base
  def analytics(authenticatable: current_consumer_user || current_producer_user)
    @analytics ||=
      case authenticatable
      when ->(a) { a.is_a?(ConsumerUser) }
        ConsumerUser::Analytics.new(
          consumer_user: authenticatable,
          browser: browser.name
        )
      when ->(a) { a.is_a?(ProducerUser) }
        ProducerUser::Analytics.new(
          producer_user: authenticatable,
          browser: browser.name
        )
      end
  end
end
```

It's not the end of the world, but it does require these polymorphic disambiguators that can make things a bit hard to reason about. If there's interest from the team I can work to put together a PR to allow for a dynamic `parent_controller` option. Thanks.
