### ISSUE TITLE
Devise::RegistrationsController#create and #update only yield to block on success

### ISSUE THREAD

**Issue by dpehrson** [plataformatec/devise#2936]
Howdy all,

While making use of the excellent functionality introduced by #2728 I found what I think to be a bug/incomplete functionality.

in [`Devise::RegistrationsController#create` at line 16](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L16) and [`Devise::RegistrationsController#update` at line 45](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L45) the resource is only yielded to the provided block upon successful creation/update and not on failures.

In my specific use-case I need to capture failures in order to register events with my analytics engines. This is currently impossible without completely replacing the method as far as I can tell which is what #2728 was trying to fix.

I think fixing it may be as simple as doing something like this:

``` ruby
def create
  build_resource(sign_up_params)

  saved = resource.save # Save and store result
  yield resource if block_given? # Yield always, block can check resource.persisted? to detect success or failure
  if saved
    if resource.active_for_authentication?
      set_flash_message :notice, :signed_up if is_flashing_format?
      sign_up(resource_name, resource)
      respond_with resource, location: after_sign_up_path_for(resource)
    else
      set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
      expire_data_after_sign_in!
      respond_with resource, location: after_inactive_sign_up_path_for(resource)
    end
  else
    clean_up_passwords resource
    respond_with resource
  end
end
```

Does this seem reasonable? If so I will start working on a pull request.

**Comment by krnjn** [comment]
Sorry to bother with this, but on the update action, how can we know the value of `resource_updated`? In that case, `.persisted?` does not help nor does `.valid?`– is there another method I can easily swap in that I'm just not thinking about here?

**Comment by josevalim** [comment]
` .errors.empty?`?

**Comment by dpehrson** [comment]
@krnjn Digging through `resource_updated` => `update_resource` => `resource.update_with_password` the value of `resource_updated` is effectively the same as whether or not the resource is valid/saved: https://github.com/plataformatec/devise/blob/65700b22bab0746a40358dacb32197280acf2888/lib/devise/models/database_authenticatable.rb#L71

Not sure if this helps or not.

**Comment by krnjn** [comment]
Thanks @josevalim– that does solve part of the issue. The reason I wanted to pass in the variable `resource_updated`, is that I'm using the yield block to run another set of updates with an external API. In the case that that update fails, I want to set `resource_updated` to `false` so that it goes to the failed branch of the update action. 

Though `resource.errors.empty?` allows me to determine whether the resource was successfully updated in the line just above, I can't change the course of action in the `yield` block (other than manually setting a `redirect_to path and return` command– but this skips out of the other methods you all have written with this controller action).

Essentially, it'd be something like so:

```
super do |resource, resource_updated|
  if need_to_update_with_external_api
    resource_updated = resource_updated && update_with_external_api(resource)
    if resource_updated
      # run some custom actions here, set a flash message perhaps
      # enter into the `resource_updated = true` branch when finished with the yield block
    else
      # set some other flash message here
      # enter into the `resource_updated = false` branch when finished with the yield block
    end
  end
end
```

This may be way too specific for you all to worry about, but by simply passing along the `resource_updated` to that block, I think I can use the same behavior without needing to completely customize/overwrite the controller.

**Comment by dpehrson** [comment]
@krnjn Good use case.

@josevalim I realize this is a much, much larger idea, but for a long time I've wished that devise would move all this logic out of the controllers and into a service layer so the specific functionality of creating accounts, updating accounts, initiating password resets, etc. would be isolated from controllers. This would make it much easier for people to slice/dice/combine the functionality needed and allow access to it from things like Rake tasks, service objects, custom controllers, etc. Do you have any thoughts on that?

**Comment by josevalim** [comment]
Then the best is to have your own action.

The smaller functionality you ask already exists in the model today.
reset_password, find_by_token, are all the building blocks for those
functionalities. Moving to a service would still be coupled to the
controller, due to flash, params, redirects.

That's why I regret the super functionality. It makes people try to twist
Devise controllers even more, instead of rolling with their own actions.



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by dpehrson** [comment]
@josevalim That's generally what I've done in the past, the only downside is that it usually requires completely duplicating the core method's code which has bitten me in the past when upgrading devise.

Ultimately devise is one of the best and most extensible libraries I've ever worked with, so I'm mostly splitting hairs.

There's no need to continue the conversation, but maybe one day I'll put in a pull request containing changes I'd like to see for evaluation, code talks more than words!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by matsubo** [comment]
`-1`

I wrote my code expecting the passed block is only executed the resource is saved successfully.

So the my code had been executed every time even if validation of the entity was failed.

I'd appreciate if this change is shared more widely and written in CHANGELOG.

**Comment by dowi** [comment]
> @krnjn Good use case.
> 
> @josevalim I realize this is a much, much larger idea, but for a long time I've wished that devise would decouple all this logic from the controllers and into a service layer so the specific functionality of creating accounts, updating accounts, initiating password resets, etc. would be isolated from controllers. This would make it much easier for people to slice/dice/combine the functionality needed and allow access to it from things like Rake tasks, service objects, custom controllers, etc. Do you have any thoughts on that?
> 
> I'd much rather see the `Devise::RegistrationsController#create` be simplified to look like:
> 
> ```
> def create
>   result = Device::RegistrationService.create(params)
>   if result.success?
>     ...
>   else
>     ...
>    end
> end
> ```
> 
> Immediate use-cases that come to mind:
> 
> * For managing users from Rake tasks
> * For managing users from backend admin areas like ActiveAdmin
> * For use in other service objects that coordinate user management with other components
> * For use in API controllers

This is such a great idea
