### ISSUE TITLE
Confirmation token looks not valid on sign up

### ISSUE THREAD

**Issue by simo2409** [plataformatec/devise#2976]
Hello,
I have a rails 4.0.4 app with devise 3.2.2 with confirmable enabled.
When a user sign up he receives by email the confirmation email with the link to be clicked to confirm user. Clicking on this link devise answers with "invalid token".

If the user requests confirmation email again, clicking on the link it works as expected.

I have not customized anything devise-related so I have no idea why this difference between "confirmation-on-sign-up" vs "confirmation-on-request"

Thank you!

**Comment by dasheck0** [comment]
We also encountered this problem. We did the following: Devise provides an after confirm hook called `after_confirmation`, which was sufficient for our needs, since we wanted to set some properties for the user when he uses them (after he confirmed his account successfully). Hence we moved the code from the after_create to the after_confirmation method and it worked out as intented.

Since this will not work for every usecase, since some of them want to set properties directly after creation and before confirmation in particular, but I hope this will help some of you.

Best regards

**Comment by littleforest** [comment]
I just ran into this issue and created a brand new Rails app to test.  I found that if I use ```build``` in the after_create statement then I have the problem of the unconfirmed_email getting set.  My simple setup was as follows:

```ruby
# app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :projects
  after_create :add_project

  private

    def add_project
     # Using create DOES NOT set the unconfirmed_email and 
     # thus I can confirm my user with no problem
     # self.projects.create(name: "foo")

     # Using build DOES set the unconfirmed_email and 
     # thus my confirmation always fails.
     self.projects.build(name: "foo")
     self.save
    end
end
```

```ruby
# app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
end
```

**Comment by dasheck0** [comment]
When you build a project the user model is affected, because of the relation to the project model. But the "problem" is the save method you call on the user model. Once you save the model the confirmation token gets regenerated and therefore every mail you sent with the (now) old token is useless. 

Again we solved this by moving all the code to the after_confirmation method, which gets called once the user is confirmed. This might be also a solution for your situation, since I user is only allowed to work on projects after he is confirmed (I suppose). Therefore add the project onla after confirmation.

**Comment by littleforest** [comment]
I understand that this may not be a bug, but it is very difficult to figure out why confirmable is not working in this case. Determining that the after_create on the user model is the problem feels somewhat obscure.  Googling the issue brings up posts regarding the switch from the secure to the insecure token which was not the problem.  I had to then go through the Devise gem itself until I realized that the postpone_email_change_until_confirmation_and_regenerate_confirmation_token was also being called along with generate_confirmation_token which finally led me to an [SO post](http://stackoverflow.com/q/22238786/1753903) that highlighted that the after_create method was the problem.  Moving the code to the after_confirmation method is fine except when you want to allow your user to use the site immediately without confirming right away, or when you only want something to happen once and then you have to modify the after_confirmation method to deal with reconfirmation.  Is there absolutely no way around this?  At the very least can a note be added (I'm happy to do so) to the [wiki post on adding confirmable](https://github.com/plataformatec/devise/wiki/How-To:-Add-:confirmable-to-Users) that an after_create method on the user model may contribute to confirmable not working properly to save some people a couple hours of digging?  Or perhaps a new wiki page altogether outlining the issue and how you can move things to after_confirmation method and also handle reconfirmation a la [this post](http://stackoverflow.com/a/21011987/1753903).

**Comment by lucasmartins** [comment]
:hurtrealbad:
