### ISSUE TITLE
NoMethodError in Devise::Sessions#new

### ISSUE THREAD

**Issue by hiveer** [plataformatec/devise#2993]
I upgrade my session store to `memcached` and use `gem 'dalli'`. Here is the config.
 /config/initializers/session_store.rb

```
QYBUser::Application.config.session_store ActionDispatch::Session::CacheStore, :expire_after => 20.minutes
```

/config/environments/production.rb[/config/environments/development.rb]

```
config.cache_store  = :dalli_store, nil, {:namespace => "QYBUser", :expires_in => 1.day, :compress => true}
```

/config/environment.rb

```
ENV["MEMCACHE_SERVERS"] = "192.168.1.189:11211:5, 192.168.1.199:11211:5"
```

Then, comes the error

```
undefined method `split' for nil:NilClass

 <h2>Sign in</h2>

  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <div><%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %></div>

app/views/devise/sessions/new.html.erb:3:in `_app_views_devise_sessions_new_html_erb__473235439_112269650'
```

**Comment by codebycliff** [comment]
For future people reading this thread:

I had a similar error (`undefined method 'split' for nil:NilClass`) after a bundle update including devise 4.3.0. Since the error was happening when calling `update` on my user model, I assumed it was a devise issue. My initial search lead me to this thread. After further looking into it, it turned out to be an issue [with this pull request](https://github.com/MiniProfiler/rack-mini-profiler/pull/291/files) to `rack-mini-profiler` which they've since reverted.
