### ISSUE TITLE
not_found_in_database key shouldn't need a password to be triggered

### ISSUE THREAD

**Issue by elomarns** [plataformatec/devise#3021]
I was analysing the default devise.en.yml file and the key not_found_in_database grabbed my attention. Its name indicates that this will be the message shown when an unregistered user tries to sign in. However this key will be used only on cases where a password was provided, which isn't a obvious behaviour to me.

I believe a key named not_found_in_database should refers to the scenario where the user doesn't exist, without any checks about the presence of a password.

To do so, I believe a single change in the file  lib/devise/strategies/database_authenticatable.rb would be enough.

Current line 8 of lib/devise/strategies/database_authenticatable.rb:

``` ruby
resource  = valid_password? && mapping.to.find_for_database_authentication(authentication_hash)
```

Proposed change on line 8 of lib/devise/strategies/database_authenticatable.rb:

``` ruby
resource  = mapping.to.find_for_database_authentication(authentication_hash)
```

**Comment by j15e** [comment]
I also think that sending the `not_found_in_database` error without really checking the email in the database because no password was provided is misleading for a user if his account does exist. We get client support request because people think their account was lost and then they cannot subscribe again (because it does exist).

I will change my strategy in my code for now, but I would suggest this change for devise :

```ruby
fail(:not_found_in_database) unless resource
# changed to
fail(:not_found_in_database) unless mapping.to.find_for_database_authentication(authentication_hash)
```
