### ISSUE TITLE
:confirmable lets login unconfirmed

### ISSUE THREAD

**Issue by DmitriySalko** [plataformatec/devise#3244]
Hello 

I've found out that `````:confirmable````` may work incorrect.

I have following config
`````config.allow_unconfirmed_access_for = 2.days`````

And it appears that after 2 days it doesn't let user in, but if user request new confirmation email it allows him to login without confirmation. So, in theory it's possible to use unconfirmed account for infinite time, just requesting new confirmation before login.

Maybe a bug. Any suggestions?

Thanks.

**Comment by josevalim** [comment]
In the past we were used to not allow it but it caused further issues because some accounts may require information for confirmation that can only be accessed logged in. We would need a redesign of the confirmation system for this to work for both scenarios however that is not planned any time soon. :S
