### ISSUE TITLE
signed_up_but_unconfirmed message not displayed after signup

### ISSUE THREAD

**Issue by benbonnet** [plataformatec/devise#3253]
Small problem on the users signup,
I'd like to display the correct message when a user signs up and has to confirm.

As of today, after a user successfully signs up but still has to confirm,it redirects to the login page (this might be okay), but displays devise:failure:unauthenticated message instead of the expected devise:registrations:update_needs_confirmation

The confirm email is correctly sent and received and when the link is clicked, it confirms the account and I'm able to login.

Sorry to ask if it is an obvious one;
Is there any kind of infos on my setup to provide in order get some help right here ?

**Comment by jez** [comment]
I know this issue is closed and the GitHub issues is not the place for troubleshooting, but after following @josevalim's advice above, I ended up at the Devise wiki, specifically [this page](https://github.com/plataformatec/devise/wiki/How-To:-Redirect-to-a-specific-page-on-successful-sign-up-%28registration%29) that explained exactly what to do (for all the people that are reaching this page from a search engine result).

Thanks for an awesome project!
