### ISSUE TITLE
Potential issue with with_reset_password_token

### ISSUE THREAD

**Issue by lfportal** [plataformatec/devise#3403]
Hi there, we are currently using version 3.4.1 of the Devise Gem with RoR 4.1. When we reset a users password we use the class method

with_reset_password_token in Recoverable.rb to retrieve the user as follows;
user = User.with_reset_password_token(params[:token])

In this method

# Attempt to find a user by password reset token. If a user is found, return it
# If a user is not found, return nil
def with_reset_password_token(token)
  reset_password_token = Devise.token_generator.digest(self, :reset_password_token, token)
  to_adapter.find_first(reset_password_token: reset_password_token)
end

The user find fails as reset_password_token changes from the original without a value change in the Db as a result the find_first fails. Can anyone explain this? Is this a bug. According to the Ruby documentation OpenSSL::HMAC.digest(digest, key, data) is supposed to generate a new token from data. The method comment alludes to the fact this method should return a user using the original token, but it appears not to work.

**Comment by josevalim** [comment]
Devise always encrypt the cookies before we store them to the database, so we need to encrypt them when trying to fetch them!

If you think this is still a bug though,  You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by Sirpez** [comment]
May I relive this, I'm having a problem with this method now. Don't know if i'm being dumb. Let's go through what I did:

1. Made a request asking to reset the password;
2. Received the email with the link and clicked it;
3. This link passes the reset_password_token as a parameter in the URL;
4. The action in the controller calls the "with_reset_password_token" function passing the reset_password_token found in the URL parameters;
5. The function returns nil

So I used byebug to understand what's happening, why is it returning nil. Ill share what I did in the terminal:
```
(byebug) a = resource_params[:reset_password_token]
"32Aa4eEdkzpSJ6_64j17"

(byebug) User.second.reset_password_token
CACHE User Load (0.1ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1 OFFSET $2  [["LIMIT", 1], ["OFFSET", 1]]
  ↳ (byebug):1
"32Aa4eEdkzpSJ6_64j17"

(byebug) resource_class.with_reset_password_token("32Aa4eEdkzpSJ6_64j17")
  CACHE User Load (0.0ms)  SELECT  "users".* FROM "users" WHERE "users"."reset_password_token" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["reset_password_token", "b0f57ba23b9e40d8e14bee6cffcc8f6dd32666aedca552fe7145a6c426d73caa"], ["LIMIT", 1]]
  ↳ (byebug):1
nil
```

So that's what I found out, the field of the user in the database is not being digested when saved to the DB, and when the ``with_reset_password_token`` function digests the token and searches the user the fields wont match. I do think the problem is something I'm doing hahah as this is commonly used by everybody who uses this awesome gem (including my past self in past projects).

Thanks!
