### ISSUE TITLE
Confirmation token handled differently between prod and dev

### ISSUE THREAD

**Issue by AdrienGiboire** [plataformatec/devise#3408]
For some reasons, the confirmation token send in production is the one saved in database, so obviously it won't work when a user will try to confirm his email. What's stranger is that I have no problem on any development machine.

I've checked: same devise version (3.2.2), no cache issue (who knows), same ruby version (2.1.5)

Does anyone has an idea where I should look for?

**Comment by josevalim** [comment]
Thanks you for the report. Confirmation token is working fine in our production apps. That said,  Can you please provide a sample application that reproduces the error?

**Comment by AdrienGiboire** [comment]
That's quite the thing, I don't know how to reproduce it. If I could, I guess I would know how to fix it. I was mostly asking for hints. Something I might have missed.

**Comment by josevalim** [comment]
@AdrienGiboire :) I was going to say exactly the same thing, if we knew something that was causing an issue with those constraints, it would likely be a devise bug which we would have fixed. The most likely is that there is something specific to your application, another gem, a customization, that is affecting how devise works. That's why we ask a way to reproduce the error in a new application.

**Comment by AdrienGiboire** [comment]
Thanks for your time anyway and sorry for wasting it :'(

**Comment by josevalim** [comment]
Nah, it is ok! I was not precise in the beginning, so miscommunication happens! Have a good one!
