### ISSUE TITLE
when trying to sign out ActionController::InvalidAuthenticityToken in Devise::SessionsController#destroy

### ISSUE THREAD

**Issue by ssoulless** [plataformatec/devise#3461]
devise 3.4.1
Rails 4.1.9

How to reproduce

1. open a tab1 in your browser and log in to the app with user1
2. open the app in another tab2
3. log out from tab2
4. log in with another user2 from tab2
5. go to tab1 and try to log out. 

I tried to look in the issues queue, and I found similar threads, I tried a lot of them and they are already fixed. But with the procedure I exposed above still the problem persists

That should not be the behavior, I think it should redirect, or show a flash message like "Your session expired" and then log out user2 too, I do not know.

Thanks

**Comment by josevalim** [comment]
Signing in and signing out update our CSRF token for security reasons, so the issues you have mentioned will show up. We can't automatically sign the user out though because it would be indistinguishable from an attack, so failing is likely the best we can do. At best, you could have a custom controller that rescue the error and re-renders the login page (or something similar).

**Comment by ssoulless** [comment]
Ok, but we can do something similar
