### ISSUE TITLE
Method scope confirmable vs recoverable

### ISSUE THREAD

**Issue by iamWh1sp3r** [plataformatec/devise#3533]
Hi, is there a reason why the `#confirmation_period_valid?` method is protected while the `#reset_password_period_valid?` method is public? This difference occured to me when trying to use it in a controller.

**Comment by carlosantoniodasilva** [comment]
It is because the [current recoverable logic relies on the `reset_password_period_valid?` method to be public](https://github.com/plataformatec/devise/blob/v3.4.1/lib/devise/models/recoverable.rb#L132), otherwise it'd be protected I think.

I don't think there's need to broaden the public api that devise already has, but you can easily make the method public in your own model by calling something like `public :confirmation_period_valid?` if you need to, or encapsulate that call into another method.

Thanks.
