### ISSUE TITLE
Should not the default email regex be the same as Rails 

### ISSUE THREAD

**Issue by ybart** [plataformatec/devise#3537]
I have one user which was able to register with an email that looks like the following (we don't use email confirmation on our application) :

```
pxxx@oxxx.xxx,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,à
```

(I've substituted some characters with x for obvious confidentiality reasons)

I assume that Rails EmailValidator is not used for compatibility reasons.

In EmailValidator the regexp used by Rails looks like this :

```
/\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
```

The one from Rails is the following :

```
/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
```

After looking at #3376, I understand that the user part might need to be loose, but I don't see any problem having a more strict validation for the domain part.

If nobody disagrees with this, I would be happy to publish a pull request for this.

**Comment by carlosantoniodasilva** [comment]
As far as I remember, Rails does not provide an email validator, it contains one used on Active Model tests and some examples on how to do that with format validation on the docs if I'm not wrong, but that's about it.

In any case, email validation is somewhat controversial, it may vary from app to app, so if Devise does not seem to provide enough confidence for you in this validation, you can just [change the default regexp in your devise config](https://github.com/plataformatec/devise/blob/v3.4.1/lib/devise.rb#L120-L124).

Unfortunately I don't think Devise is changing it's default email regexp, also because it may also break other applications when they upgrade. Thanks!

**Comment by ybart** [comment]
I've done that. Thanks you !
