### ISSUE TITLE
URL postfix

### ISSUE THREAD

**Issue by Conroy94** [plataformatec/devise#3571]
This doesn't seem like it's been reported before, so I'm going to assume it's not actually a bug, but rather something I'm doing wrong.

```ruby
Rails.application.routes.draw do
  devise_for :users, skip: [:sessions]

  as :user do
    get 'sign-in' =>         'users/sessions#new',       as: :new_user_session
    post 'sign-in' =>        'users/sessions#create',    as: :user_session
    delete 'sign-out' =>     'users/sessions#destroy',   as: :destroy_user_session
  end

  root                       'static_pages#home'
end
```

The routes seem to work fine, as I can visit http://localhost:3000/sign-in. However, any links or form submissions to other pages result in the URL having ".user" at the end. For example, on the sign in page, the "Sign up" link is http://localhost:3000/users/sign_up.user, and the "Forgot your password?" link is http://localhost:3000/users/password/new.user

I tried removing the custom routes by just having this:
```ruby
Rails.application.routes.draw do
  devise_for :users

  root  'static_pages#home'
end
```

and the URLs still have ".user" at the end.

Any help is much appreciated.

**Comment by josevalim** [comment]
That's because you are passing the some user as information to your URL helpers and they don't need it. Verify how you are calling the url helpers and you shuold be good.

Also,  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
