### ISSUE TITLE
User.reset_password_by_token doesn't seem to work.

### ISSUE THREAD

**Issue by xingle** [plataformatec/devise#3600]
reset_password_token was 9e9a04d97752d67e2bef938d36bf43bd99d6d0dd7263a0cd4f00313ab559dca1, but it doesn't update password.

Parameters: {"user"=>{"password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "reset_password_token"=>"[FILTERED]"}, "password"=>{"user"=>{"password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "reset_password_token"=>"[FILTERED]"}}}

User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."reset_password_token" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["reset_password_token", "fcab88a798715ba31dbfe6f63223e0033ff6e7b6efb1355ca081dcbd1ae5278f"]]

**Comment by josevalim** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by xingle** [comment]
I was going to implement reset password with REST API.

My custom passwords controller looks like following.

def update
    user = User.reset_password_by_token(params[:user])
    if user.errors.empty?
      render json: {}
    else
      respond_with_namespace(user)
    end
  end

but it doesn't seem to update password.

**Comment by telkomsel13** [comment]
#3600

**Comment by xingle** [comment]
I solved this issue.
I had to use @token variable on the reset_password_instructions mailer instead of @resource.reset_password_token

**Comment by cesc1989** [comment]
Thanks @xingle I realized I was on a bad approach.

I was trying to find the user(`User.find_by_reset_password_token(token)`) with the value `@token` sent in the email but no user could be found. Checking the database I could see that `User.find(1).reset_password_token` was not the same as `@token`.

When I used `@resource.reset_password_token` rather than `@token` in the email template, finder `User.find_by_reset_password_token` worked but I see that it could be wrong sending the plain hash in a email.

So, the right approach is given by the method you use `User.reset_password_by_token(params)` which uses the filtered-hash passed in the email to find the user and update its password.

Know I wondered where you found `reset_password_by_token` method. I have not found it in the docs.

**Comment by woahstorkdork** [comment]
@cesc1989 you can find the reset_password_by_token method [here](http://www.rubydoc.info/github/plataformatec/devise/Devise/Models/Recoverable/ClassMethods) in the following Module: Devise::Models::Recoverable::ClassMethods. Keep in mind that the Devise.token_generator.generate method returns an encrypted token and a raw token. This is probably why the token @chollimee was using wasn't matching/working. Sorry to chime in so late, but just came across this comment and hopefully it is useful to somebody in the future.
