### ISSUE TITLE
Regenerate password hash on change to stretches or pepper

### ISSUE THREAD

**Issue by reedloden** [plataformatec/devise#3635]
When a user logs in, check to see if his/her hash is using the most current `stretches` and `pepper` values, and if not, regenerate the password hash (using the raw password value available at log in). This allows old password hashes to keep working while supporting an easy way for an application to migrate users to more secure hashes over time.

**Comment by josevalim** [comment]
We don't support password upgrades in Devise but they are Devise extensions that do. :) That's what we recommend for now. Also, pepper is a legacy, we don't really use pepper for bcrypt which is Devise the de-fact encryptor.

**Comment by reedloden** [comment]
I don't see anything on https://github.com/plataformatec/devise/wiki/Extensions that looks like it would do that. Do you know of a specific extension?

**Comment by josevalim** [comment]
The wiki is not a compreheensive list. I definitely recall something being released but it may have been a long time ago. :S

**Comment by aried3r** [comment]
> We don't support password upgrades in Devise but they are Devise extensions that do. :) That's what we recommend **for now**.

Does "for now" (emphasis mine) mean that there is a possibility this will be added to Devise? Since most recently the stretches for bcrypt were increased, I wanted to migrate, but saw that all PRs so far were closed and about 4 years ago, [this shouldn't be part of Devise](https://github.com/plataformatec/devise/pull/1862#issuecomment-5799967). Do you still think so?

Because all the PRs I could find patched Devise itself and didn't use existing callbacks. If possibly, I'd prefer a solution that doesn't require me monkey patching Devise. :)
