### ISSUE TITLE
Resend a invitation email when expired does NOT update created/sent_at

### ISSUE THREAD

**Issue by conichi-developers** [plataformatec/devise#3637]
When an invitation link sent by mail is expired, re-deliver the invitation doesn't update the created_at and sent_at timestamp and so all the new tokens are not valid.

**Comment by carlosantoniodasilva** [comment]
By invitation I imagine you're using devise-invitable? There's nothing about invitations in devise itself.

Please clarify, and if it's a devise issue add some code to show what might be going on, so that we can try to help. Meanwhile I'll close this, and I'll gladly reopen if it's devise related. Thanks.
