### ISSUE TITLE
Exception after upgrading to rails 4

### ISSUE THREAD

**Issue by shlomitsur** [plataformatec/devise#3724]
Hello

I"m getting this error when logging-in with devise:

Mysql2::Error: Incorrect datetime value: '?' for column 'remember_created_at' at row 1: UPDATE `users` SET `remember_created_at` = '?', `updated_at` = '?' WHERE `users`.`id` = 1

I've upgraded to rails 4 from 3.2.1 and to devise 3.0.0.rc from 2.2.7 

Thank you

**Comment by carlosantoniodasilva** [comment]
You need to give us more information or a way to reproduce the problem, otherwise it's hard for us to help. Also please keep in mind it'll be probably better not to use the rc version of devise, try to go to a final/stable released version, and be sure the check the changelogs to see what has changed between versions. If you need more help, please try the mailing list or stack overflow first, we reserver the issues tracker for issues - so if you do think you find an issue, we'll be glad to help over here. Thanks!
