### ISSUE TITLE
devise_group in application controller causing error

### ISSUE THREAD

**Issue by CodingMonkeyXYZ** [plataformatec/devise#3757]
Sorry if this is a duplicate or I'm just missing something obvious but I've created a simple devise app with a user model that's extended via STI to two other classes and I have this in my application controller:

devise_group :users, contains: [:managers, :employees]

But I can't get the app to even start because it complains:

NoMethodError: undefined method `devise_group' for ApplicationController:Class

Is this a bug or do I have to manually include the class?

More details here: http://stackoverflow.com/questions/32612900/trying-to-create-multiple-devise-models-and-grouping-them-with-devise-group

**Comment by josevalim** [comment]
There is no `devise_group` method in Devise at all. Why are you thinking there is one? If you believe there must be one, then it would be from a plugin or extension, not from Devise.

**Comment by MagicalMonkey** [comment]
http://www.rubydoc.info/github/plataformatec/devise/master/Devise/Controllers/Helpers/ClassMethods:devise_group

?

**Comment by MagicalMonkey** [comment]
Could you re-open the issue please? I've pointed right to the area of the documentation where it is. It's a new-ish feature but I don't believe it's working.

**Comment by josevalim** [comment]
Which Devise version are you using?

**Comment by MagicalMonkey** [comment]
devise 3.5.2

**Comment by MagicalMonkey** [comment]
It works within a controller I create but not the application controller.

  class NotesController < ApplicationController  
    before_action :authenticate_user!
    before_action :set_note, only: [:show, :edit, :update, :destroy]
    devise_group :user, contains: [:manager, :employee]
     .....

Works but....

  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    devise_group :user, contains: [:manager, :employee]
  end

Doesn't. It generates this error:

  Exiting
  ...../application_controller.rb:9:in `<class:ApplicationController>': undefined method `devise_group' for ApplicationController:Class (NoMethodError)

**Comment by lucasmazza** [comment]
@MagicalMonkey can you please provide a sample app that reproduces the error?

**Comment by MagicalMonkey** [comment]
Sure, this is a simple app generated mostly via rails composer, I've added two subclasses of user model and tried to join them together with User with devise_group: https://github.com/MagicalMonkey/devise_group_test

I tried setting config.parent_controller = "ApplicationController" in the config, because someone hinted at that being an issue but that didn't seem to fix anything. Maybe I'm doing it wrong.

Perhaps I've got the wrong end of the stick in assuming you can use this in the main app's ApplicationController? Is the point of devise_group to control authorisation for individual 'engines' rather than the app as a whole?

**Comment by themantalope** [comment]
I'm having the same problem as @CodingMonkeyXYZ, however I noticed something peculiar. When I try to start the rails server or run `rake routes` with the `devise_group` line in my ApplicationController, I get the same errors as discussed above. However, if I comment out the `devise_group` line, allow the sever to start and **then uncomment out the `devise_group`** line, everything works as expected. Could it be a problem with the way Rails initializes devise and the helper methods at application startup?

**Comment by themantalope** [comment]
Ok, a little more playing around and if I put this line of code in at the top of the ApplicationController file: `include Devise::Controllers::Helpers::ClassMethods`, everything works as expected with no error about an undefined `devise_group` method. Now, as @CodingMonkeyXYZ  stated previously, shouldn't these helper methods be available to the application controller automatically? Is it because they are inside of the `ClassMethods` module that the ApplicationController isn't able to access it? Or is it because `devise_group` was not declared as a helper method in line 10 of file https://github.com/plataformatec/devise/blob/1a0192201b317d3f1bac88f5c5b4926d527b1b39/lib/devise/controllers/helpers.rb?

**Comment by CodingMonkeyXYZ** [comment]
Well, either the code is broken or the documentation is....

'#Those helpers are convenience methods added to ApplicationController.'

**Comment by lucasmazza** [comment]
@CodingMonkeyXYZ your sample app has an initializer that forces the loading of `DeviseController` and `ApplicationController` before the app is properly initialized, causing the exception - deleting https://github.com/CodingMonkeyXYZ/devise_group_test/blob/master/config/initializers/devise_permitted_parameters.rb solves the loading order, and it is recommended to customize the Parameters Sanitizer API through your controllers instead of an initializer like this.

@themantalope do your app has a similar scenario?

**Comment by themantalope** [comment]
Hi @lucasmazza thanks for taking a look at this. My app does use a `devise_permitted_parameters.rb`initializer - I haven't had a chance to test your suggestion out yet but when I do I will let you know.
