### ISSUE TITLE
Model migration is generated without .rb extension

### ISSUE THREAD

**Issue by Stormcore** [plataformatec/devise#3759]
rails generate devise User
produces
 create    db/migrate/20150920140432_devise_create_users
 create    app/models/uber_user.rb

as we can see, migration is without extension and is not recognized by rake db:migrate

**Comment by lucasmazza** [comment]
If you are using Rails 4.1+ this was fixed back in Devise 3.2.3. 

Otherwise if you are facing this with recent versions of Devise, you need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. 

Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
