### ISSUE TITLE
Support instance method version of allow_unconfirmed_access_for

### ISSUE THREAD

**Issue by vemv** [plataformatec/devise#3781]
It's great to override `self.allow_unconfirmed_access_for` in one's resource class.

I'd like the same but at instance level though: e.g. some users may need immediate confirmation, while others may enjoy a 1 hour grace period, depending on their _role_ (or anything else only accessible at instance-level only).

Seems easy to implement (`Devise::Models::Confirmable#confirmation_period_valid?`). Logically the instance value would have precedence over the class value.

Thoughts?

Cheers - Victor

**Comment by lucasmazza** [comment]
@vemv have you tried adding the `allow_unconfirmed_access_for` instance method to your class? Since it is a config defined through [`Devise::Models`](https://github.com/plataformatec/devise/blob/19b1e2a6bc6bacf9b1566a666e561e45d7209910/lib/devise/models/confirmable.rb#L324) it should be availble as an [instance method](https://github.com/plataformatec/devise/blob/19b1e2a6bc6bacf9b1566a666e561e45d7209910/lib/devise/models.rb#L13-L28) for you to override it and customize it as necessary.
