### ISSUE TITLE
devise errors too hard to style

### ISSUE THREAD

**Issue by Tectract** [plataformatec/devise#3832]
Don't have hours to figure this out, don't wan't the crappy default error message styles on my nice site.

**Comment by lucasmazza** [comment]
As stated in the [docs](https://github.com/plataformatec/devise/blob/d22ac4a4fb304ea93c728efe955535cb6b8b6a86/app/helpers/devise_helper.rb#L2-L4), we recommend you to write your own helpers/markup in case you need any customization of the error message.

**Comment by Tectract** [comment]
That is far, far too hard for any laymen to figure out, or even find. It should be easy to customize error messages, not insanely, insanely hare. This ticket should be re-opened.

**Comment by josevalim** [comment]
@Tectract at the end of devise:install, we now ask users to copy the views to your application. If you do it, you can just go and change the view.

> That is far, far too hard for any laymen to figure out, or even find. It should be easy to customize error messages, not insanely, insanely hard. 

Thank for the feedback. We will keep an eye on it and see if others have the same complaint so we can take the best action.

**Comment by josevalim** [comment]
Also, if you don't have hours to figure something out, it is ultimately your fault. Not ours. Be nice, we are always willing to help. We have plenty of material on the topic.

* Page on the wiki: https://github.com/plataformatec/devise/wiki/Override-devise_error_messages!-for-views
* Discussion on stack overflow: http://stackoverflow.com/questions/4101641/rails-devise-handling-devise-error-messages
* And documentation too: [http://www.rubydoc.info/github/plataformatec/devise/DeviseHelper:devise_error_messages!](http://www.rubydoc.info/github/plataformatec/devise/DeviseHelper:devise_error_messages!)

**Comment by Tectract** [comment]
Yeah, that seems like a pretty ridiculous attitude to me. The docs are really flimsy there and referring to SA question thread just exhibits more laziness to me. I think you can judge the quality of a piece of software largely by the documentation, and what I see here is the most half-assed possible effort to document a widely-used feature that is poorly supported, and a defensive attitude to newcomers who don't have time to re-invent the wheel because every damn gem tries to include some shitty styles.

**Comment by josevalim** [comment]
We have shown where the documentation exist, because you mentioned there was none, and a couple others link too. We have been open to change and asked for contributions while you have just been rude towards the maintainers of the project which you are using.

If you don't have time to help to contribute, at least be nice. That's the only thing we ask, really.

**Comment by Tectract** [comment]
I'm just pointing out that the documentation here is basically little more than a hand-waiving at the source code with no real explanation of how to actually *customize* the error messages. It needs work. The fact that there are huge long threads of confused people should be your indication that it needs improvement, not content for your FAQ.

**Comment by PragTob** [comment]
@Tectract devise is open source and provided to you free of charge, the people at plataformatec put ridiculous amounts of work into it so you can have a nice standard authentication solution that "just works" (tm). The least you could do in my opinion is show some appreciation for what they do and thank them. Imo in the open source spirit I think it'd be nice for you to help out with the docs. They don't have to, for lots of them it's a free time activity. You could start a bountysource bounty if it is that important to you. The reaction to getting free things should not be "NOW GIVE ME MORE OF THAT" but rather constructive and nice. Also, you don't have to use devise. There are other options out there. You could also roll your own, but I'm sure that'd take more time than adjusting devise error messages.

On that note, thanks @josevalim @lucasmazza and company - have used devise for a variety of projects and it has always been a pleasure and made me develop applications much faster than it'd otherwise have been. :heart: :heart: :+1: :+1: :rocket: :dancer: 

Cheers and love,
an open source maintainer

**Comment by josevalim** [comment]
Thanks @pragtob. :heart:

PS: I am locking this because comments were being edited. Contributions are always welcome, just please don't expect us to do the work, specially if you start the issue by saying you can't do it yourself.
