### ISSUE TITLE
remember_expired? removed in 3.5.4 with no replacement?

### ISSUE THREAD

**Issue by mattbrictson** [plataformatec/devise#3903]
Hi, I see that the public `remember_expired?` method was removed in 3.5.4 (commit c92996646aba2d25b2c3e235fe0c4f1a84b70d24). Do you have any recommendations for how I should migrate application code that depended on this method?

**Comment by manuelpradal** [comment]
:+1:

**Comment by josevalim** [comment]
I am sorry, I didn't realize it was public API. It is a breaking change when it should not have been.

In any case, the `remember_expired?` is pretty much useless now because there is no way to know if the remember is expired. The value is stored per cookie. What are you using it for? Depending on your use case we may have a better API.

**Comment by josevalim** [comment]
I will do a 3.5.5 release soon with it brought back, even though it won't be as useful as before. Thanks for the report!
