### ISSUE TITLE
password_length not working correctly when password's length is more than 64.

### ISSUE THREAD

**Issue by itsSaad** [plataformatec/devise#3932]
i have `config.password_length = 8..128`
But when i change my password with more than 64 char. i think it only saves 64 chars. it ignores the char after 64th. I can signin even i add char after 64th that are not part of the set password.

**Comment by josevalim** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by priit** [comment]
Thank you providing and developing Devise, keep up good work!

We did have security audit for our built system, what is using at the security audit time Rails version 4.2.10 and Devise version 4.3.0.

The source code can be viewed at https://github.com/hariduspilv/harid 

In short password authentication checks the overlap of the first 72 characters, the rest will be ignored.

Description: if the user adds a long password to exactly 128 characters in the password, the authentication does not check the differences, which comes after 72 character.

Challenging functionality:
For example, a valid password for the maximum length (128):
pc7MsWX82dJAgeADEXLNiFz50Kw0XHV9KM9PS7yoJyiikmkypCAtrgWqhs63YKQWmxc3eQNbvZmAm16Bt2pc7MsWX82dJAgeADEXLNiFz50Kw0XHV9KM9PS7yoJyiik

Password for authentication (72 characters):
Ac7MsWX82dJAgeADEXLNiFz50Kw0XHV9KM9PS7yoJyiikmkypCAtrgWqhs63YKQWmxc3eQNb

For example, passes whatever you put after 72 characters:
Ac7MsWX82dJAgeADEXLNiFz50Kw0XHV9KM9PS7yoJyiikmkypCAtrgWqhs63YKQWmxc3eQNb-mis-
any-after-72.-symbol-comes

Password that can not authenticate (71 characters):
Ac7MsWX82dJAgeADEXLNiFz50Kw0XHV9KM9PS7yoJyiikmkypCAtrgWqhs63YKQWmxc3eQN

Probably it's related encryption algorithm but not sure yet.

Alternatively perhaps we should change Device default values current maximum from 128 to 71, because there is no point entering 128 length passwords at the moment when 71 length will do.
