### ISSUE TITLE
Devise gem make postgres db connection open with pg gem via net-ssh-tunnel hang

### ISSUE THREAD

**Issue by ianformanek** [plataformatec/devise#3935]
Requiring devise in a ruby project that uses net-ssh-tunnel and pg gems to do DB connection via ssh tunnel causes the process to hang and needs to be killed with SIGKILL.

Here is a sample code that demonstrates the problem: works perfectly fine, until the `require 'devise'` line is uncommented. Note that MySQL connection woks perfectly fine, just the Postgres one has problems.

Gemfile:
```
source 'https://rubygems.org'

gem 'devise', git: 'git://github.com/plataformatec/devise.git'
gem 'rails'
gem 'pg'
gem 'mysql2'
gem 'net-ssh-gateway'
```

test.rb: (needs to be modified where indicated via comments to run)
```
require 'net/ssh/gateway'
require 'pg'
require 'mysql2'
#require 'devise'

gateway = Net::SSH::Gateway.new(
  '127.0.0.1', # or other hostname to ssh to
  '', # Add username
  onfig: false,
  keys_only: true,
  port: 20,
  key_data: '' # add private key that allows to connect to the host with that username
 )

port_pg = gateway.open('127.0.0.1', 5432)
port_mysql = gateway.open('127.0.0.1', 3306)

mysql = Mysql2::Client.new(
  host: '127.0.0.1', # or hostname of the DB server as reachable from the tunnel server
  port: port_mysql,
  database: '', # add DB name
  username: '', # add DB user
  password: ''  # add password
)

puts mysql

pg = PG::Connection.open(
  '127.0.0.1', # or hostname of the DB server as reachable from the tunnel server
  port_pg,
  "",
  "",
  '', # add DB name
  '', # add DB user
  ''  # add password
)

puts pg

```

Execute with devise commented out:
```
bundle exec ruby test.rb
#<Mysql2::Client:0x007f80ab5bb660>
#<PG::Connection:0x007f80ab228250>
```
Execute with devise uncommented:
```
$ bundle exec ruby test.rb
#<Mysql2::Client:0x007fa5cbb90fc8>
Process hangs and does not respond to SIGINT (Ctrl+C), needs to be killed with SIGKILL
```

Environment:
```
OS: Ubuntu 14.04 or MacOS X
Ruby version: 2.2.4
Rails version: 4.2.5.1
net-ssh: 3.0.2
net-ssh-gateway: 1.2.0 
Devise: 4.0.0-dev (latest)
pg: 0.18.4
```

**Comment by georgeguimaraes** [comment]
Tks for the report.
I've tested your code snippet with devise master (3423043).

**ssh tunnel with `ssh host -L 5555:localhost:5432`:**

- requiring 'devise' => got a response, no hanged process.
- not requiring 'devise' => got a response, no hanged process.

**ssh tunnel with `Net::SSH::Gateway`**:

- requiring 'devise' => process hanged
- not requiring 'devise' => process hanged as well

It seems to me that the issue is not related to devise. Maybe with pg and/or Net::SSH::Gateway.

**Comment by thbar** [comment]
@ianformanek I'm debugging a similar issue (using `Net::SSH::Gateway` and `pg`). Did you find a way to make this work directly with a Ruby gateway, or did you have to use a command line instead?

(sorry to ask - it's not a devise trouble, but this problem is a bit exotic, so I thought I'd ask here!)

**Comment by ianformanek** [comment]
@thbar Unfortunately I do not have more insight as we ended up using a different approach and externalised the ssh tunnelling into a separate service.
