### ISSUE TITLE
after_sign_in_path_for return "null"

### ISSUE THREAD

**Issue by ckornaros** [plataformatec/devise#3962]
I use recoverable devise module so the user receive a mail to create a new password. When the user click on the email link, he's redirected to the device/password/edit.html.erb view. He completed the two fields and when he clicked on Validate, Devise redirect him to {root_path}null !!!
I made some investigation and I saw that the callback passed through "after_sign_in_path_for" method that return null as a string. So to fix this problem I have to do this ugly thing in application_controller.rb:

 
      
      # Devise callback after sign_in success

      def after_sign_in_path_for(resource)

            redirect_url = super

            # Redirect url is null (and not nil) on change password recovery callback

            redirect_url != "null" ? redirect_url : root_path

        end

Can you fix that ?

**Comment by ulissesalmeida** [comment]
@ckornaros Thank you for your report!

I think this issue is fixed, you can take a look at this [method](https://github.com/plataformatec/devise/blob/master/lib/devise/controllers/helpers.rb#L167). The "null" inside of the string should not happen anymore.

Could you please provide more information?

Like for example: 
* Rails version
* Devise version
* Steps to reproduce the error

Will be even more helpful if you provide a sample application or a test case that reproduces the error.

Best

**Comment by ulissesalmeida** [comment]
I'm closing this issue. Feel free to reopen if the problem persists.
