### ISSUE TITLE
Requesting confirmation instructions as authorized user will return "You are already logged in."-error

### ISSUE THREAD

**Issue by heikobornholdt** [plataformatec/devise#3969]
I've set `config.allow_unconfirmed_access_for = 365.days`. So my users can login without confirming their email.

When I go to  "request confirmation instructions"-page as authorized user and submit the form with my email address, the form will return "You are already logged in."

The confirmation instructions email was sent. However the message "You will receive an email with instructions for how to confirm your email address in a few minutes" is missing.

**Comment by carlosantoniodasilva** [comment]
That is probably because by default Devise will redirect you back to the new session path, and that will detect you're already signed in, and redirect you again to "after signed in path", with the message you see - meaning you lost the original message.

You should be able to override [`after_resending_confirmation_instructions_path_for`](https://github.com/plataformatec/devise/blob/342304375946ca11608516eae80f78dbaae059d5/app/controllers/devise/confirmations_controller.rb#L35) to determine whether the user is signed in already, and return the proper path to redirect the user in this case.

I hope that helps! Let us know if you still have any other issue.

**Comment by heikobornholdt** [comment]
Thank you for the fast response. My problem is solved :+1: 

I would suggest to change `after_resending_confirmation_instructions_path_for`, so it behaves like [after_resending_confirmation_instructions_path_for](https://github.com/plataformatec/devise/blob/342304375946ca11608516eae80f78dbaae059d5/app/controllers/devise/confirmations_controller.rb#L40-L46).
That will help other people with a similar devise configuration.
