### ISSUE TITLE
Cannot disable authentication for an engine mount

### ISSUE THREAD

**Issue by Ikariusrb** [plataformatec/devise#3977]
I'm looking at putting together a rails API backend with an ember front-end for the UI, and was hoping to use ember-cli-rails to host them as a singular rails app (for ease of full integration tests).  My plan was to use devise + ember-simple-auth for secure authentication between the front end and back end.  Unfortunately, the devise routing syntax for unauthenticated routes does not appear to mix nicely with the ember mount;

 ```
devise_for :users, controllers: { sessions: 'sessions' }

  unauthenticated do
    mount_ember_app :frontend, to: "/fe"
  end
```

still results in a 401 unauthorized when hitting my.host:3000/fe

This issue appears to apply to *any* engine mount, so there's no way to mount an engine with unauthenticated access in the same rails app where devise is hosted.

**Comment by lucasmazza** [comment]
Looking on how `mount_ember_app` works I think this will never work - `ember-cli-rails` constraint will override the constraint added by `unauthenticated` and the Rails router won't merge the two rules. 

Maybe if `ember-cli-rails` constraint was implemented as a Hash constraint instead of a callable one it could work, but I'm not 100% sure about it.

Related Rails tickets rails/rails#15668, rails/rails#19075.

Closing this as it doesn't seems to be a real issue with Devise.
