### ISSUE TITLE
sign_in(:user, store: false, bypass: true) stores the serialized user object in the session

### ISSUE THREAD

**Issue by mgwidmann** [plataformatec/devise#3981]
I ran into this bug while using the following gem:

https://github.com/lynndylanhurley/devise_token_auth/blob/master/app/controllers/devise_token_auth/concerns/set_user_by_token.rb#L59

Calling both `store: false, bypass: true` causes the user object to be serialized into the session even though store is `false`.

**Comment by mgwidmann** [comment]
You can see here that when `bypass` is true, the `options` variable is completely ignored.

https://github.com/plataformatec/devise/blob/7df57d5081f9884849ca15e4fde179ef164a575f/lib/devise/controllers/sign_in_out.rb

**Comment by ulissesalmeida** [comment]
@mgwidmann Thank you for your report.

The `options` argument is ignored because the [`Warden::SessionSerializer#store`](https://github.com/hassox/warden/blob/906edf86c6c31be917a921097031b89361d022e8/lib/warden/session_serializer.rb#L22) doest no accept this argument.

In the Devise `bypass` option [documentation](https://github.com/plataformatec/devise/blob/7df57d5081f9884849ca15e4fde179ef164a575f/lib/devise/controllers/sign_in_out.rb#L18) says it will "bypass warden callbacks and stores the user straight in session". When you use `bypass` you want to store in the session, and it has more precedence than `store: false`.

**Comment by mgwidmann** [comment]
@ulissesalmeida all im suggesting is perhaps warn or raise an error for those who attempt to use both, as it won't do what the user expects...

**Comment by ulissesalmeida** [comment]
@mgwidmann It may be a good idea. Other approach is separate in two methods, one bypass method  that doest not have the options argument and a method that don't know how to bypass. I think it is more clear. What do you think?

**Comment by mgwidmann** [comment]
seems fine to me
