### ISSUE TITLE
after_update causing tests to fail for all versions above Devise 3.5.2

### ISSUE THREAD

**Issue by connorshea** [plataformatec/devise#3992]
I ran into this issue when [attempting to update devise-two-factor to support Devise 4.0.0](https://github.com/tinfoil/devise-two-factor/pull/70).

This is the error I'm getting:
```
Connors-MacBook-Pro:devise-two-factor connor$ bundle exec rake
/Users/connor/.rvm/rubies/ruby-2.1.8/bin/ruby -I/Users/connor/.rvm/gems/ruby-2.1.8/gems/rspec-core-3.4.4/lib:/Users/connor/.rvm/gems/ruby-2.1.8/gems/rspec-support-3.4.1/lib /Users/connor/.rvm/gems/ruby-2.1.8/gems/rspec-core-3.4.4/exe/rspec spec/devise/models/two_factor_authenticatable_spec.rb spec/devise/models/two_factor_backupable_spec.rb
/Users/connor/.rvm/gems/ruby-2.1.8/gems/devise-3.5.6/lib/devise/models/database_authenticatable.rb:30:in `block in <module:DatabaseAuthenticatable>': undefined method `after_update' for TwoFactorAuthenticatableDouble:Class (NoMethodError)
```

Versions:
- Ruby 2.1.8 (also tested and affects 2.2.4 and 2.3.0)
- Devise 3.5.6 (all current versions 3.5.3 and above have this issue)

To reproduce you can run `bundle exec rake` for [this commit](https://github.com/connorshea/devise-two-factor/tree/aa7d8ab7ff1ae6747ab3cd9228477969c243324f) in my fork of devise-two-factor. The Travis CI test runs [should be available here](https://travis-ci.org/tinfoil/devise-two-factor/builds/114932561), and all three Ruby versions tested have this issue. The Travis CI builds started failing in December following the release of 3.5.3, with [a change to the README](https://travis-ci.org/tinfoil/devise-two-factor/builds/100719046), which is why I assume this is a problem with Devise rather than devise-two-factor. No related changes that would have caused this are mentioned in the CHANGELOG.

[This](https://github.com/plataformatec/devise/blob/master/lib/devise/models/database_authenticatable.rb#L30) is the line with `after_update`. It was introduced in Devise 3.5.3, thus 3.5.2 doesn't cause the tests to fail but 3.5.3+ does.  The line is added [in this commit here](https://github.com/plataformatec/devise/commit/0fa74d863d71f186c3d746ce9acdd582ba60461a#diff-19b4dd928714c72f1338874351e8ff2dR30).

/cc: @jphenow

**Comment by connorshea** [comment]
Forgot to mention, `after_update` seems to have [been deprecated a while ago](http://apidock.com/rails/ActiveRecord/Callbacks/after_update).

**Comment by lucasmazza** [comment]
APIDock is usually a misleading reference for the Rails API since it tries to summarize the docs for all available versions at once, but it can't detect all the changes between each version - itself states that the _method is deprecated or **moved**_.  You can see on the [`ActiveRecord::Callbacks`](http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html) documentation a mention to it right before the first example.

The test class [`TwoFactorAuthenticatableDouble `](https://github.com/tinfoil/devise-two-factor/blob/e59657522142bb89df95b9f4862122876a566d04/spec/devise/models/two_factor_authenticatable_spec.rb#L4-L16) need to implement the callback, and probably a [`define_model_callbacks :update`](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/callbacks.rb#L276) should do it, since we only need to have the class level macro available and not really execute the callbacks during the tests.

**Comment by lucasmazza** [comment]
Regardless of that, thanks for the incredibly well written report and the step by step work on tinfoil/devise-two-factor#70 :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by connorshea** [comment]
@lucasmazza and thank you for the help! I'm still relatively new to deeper Ruby/Rails, so I apologize if any of this is obvious to the rest of you :)

**Comment by lucasmazza** [comment]
@connorshea no problem :)

**Comment by connorshea** [comment]
@lucasmazza figured you'd like an update since I know open source can be fairly thankless. This has been added to devise-two-factor [under a devise-4 branch](https://github.com/tinfoil/devise-two-factor/commits/devise-4), thank you again for your help! :)

**Comment by lucasmazza** [comment]
@connorshea awesome work, thanks for the update :)
