### ISSUE TITLE
ActionView::Template::Error (undefined method `protect_against_forgery?'

### ISSUE THREAD

**Issue by jakesorce** [plataformatec/devise#4003]
Using Rails 5 beta3 API mode.

Getting this error when trying to do a get request to /users/sign_in route

**Comment by danielfmoreira** [comment]
Hey! I'm having the same problem

How did you fix this?

**Comment by earksiinni** [comment]
+1. How did you fix this?

**Comment by rajcybage** [comment]
I got this error

**Comment by tooppoo** [comment]
- protect_against_forgery? is defined in ActionController::RequestForgeryProtection module. This module is included by ActionController::Base.
- By default, DeviseController extends 'ApplicationController'.

ApplicationController usually extends ActionController::Base.
On Rails5 API mode, however, ApplicationController extends ActionController::API, which does not include ActionController::RequestForgeryProtection.

In order to fix, insert `config.parent_controller = 'ActionController::Base'` into config/initializers/devise.rb.

**Comment by rodriggochaves** [comment]
How you configure to all others actions to respond to JSON instead HTML when you changed to `config.parent_controller = 'ActionController::Base'`?

**Comment by tooppoo** [comment]
@rodriggochaves 
I don't longer use devise with Rails5 API mode, so not remember well what I did...
I recognize that `config/initializers/devise.rb` effects only modoules which relate to devise,
so I think `config.parent_controller = 'ActionController::Base' ` not change other controller's work.

if you will use Rails5 API mode, I recommend to use devise_auth_token. I already use it.
