### ISSUE TITLE
:validatable not working when making api requests

### ISSUE THREAD

**Issue by guaguasi** [plataformatec/devise#4089]
https://gist.github.com/guaguasi/a35d0f0a92e7b57ddc13edb0f559392b

My current setup is as shown. I'm running Rails 5 beta4, Devise 4.1, and Ruby 2.3.0. When I make a the following call from the cli, rails creates the user:

`curl --data "user[username]=test1&user[email]=test1@email.com&user[password]=12345678" http://localhost:3000/api/v1/users/register`

**Comment by lucasmazza** [comment]
@guaguasi by not working you mean the confirmation validation? If so, it's because Rails' `ConfirmationValidation` ignores `nil` values on the `*_confirmation` attribute https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/confirmation.rb#L11 - See rails/rails#22344.

If your issue with the `validatable` module is related to other validations, please be more specific on what isn't working and what is the behaviour you are expecting.

**Comment by guaguasi** [comment]
How embarrassing. Thanks, I was unaware of this. I feel that it doesn't really make sense, but it is what it is.
