### ISSUE TITLE
Why not yield resources before resource.save?

### ISSUE THREAD

**Issue by Vastorization** [plataformatec/devise#4161]
```
def create
    build_resource(sign_up_params)

    # why not here?
    resource.save
    yield resource if block_given?

   ....
end
```

so that atleast i can alter the resources before it's saved without overriding the whole stuff
i had problems where I use nested attributes and the association with presence validation which can't be save due to resources saving first.

**Comment by carlosantoniodasilva** [comment]
If you have to do many customizations, it's a lot easier to just recreate the action on your controller. You can also inherit any other method like `build_resource`or `sign_up_params`, depending on your use case (which was not very clear to me). At the end of the day, it made more sense to yield after performing the save, otherwise you couldn't make any decision based on whether the action was successful or not.
