### ISSUE TITLE
4.2.0 regression: 

### ISSUE THREAD

**Issue by TiagoCardoso1983** [plataformatec/devise#4187]
Why?

https://github.com/plataformatec/devise/blob/master/lib/devise/models/authenticatable.rb#L117-L124

I'm using `sequel-devise` and I just stumbled into this error. Because you re-defined the inspect method (but why?) and this uses `serializable_hash` , devise just broke functionality for every ORM not implementing the method (see the reimplementation of the same module). However, IMO this should be made as a conditional, as this method is only (?) implemented in ActiveRecord. `sequel` doesn't implement it. One could say it should, but sequel already goes out of its away by implementing the ActiveModel spec, which specification could be followed by devise. 

If I look a bit into it more, I'd say that `orm_adapter` should be your guide in terms of minimal ORM API supported. I'm not really against devise implementing ActiveRecord work-arounds, as long as these are protected by conditionals. So even if the `def inspect` could just be removed, there is some inconsistency there regarding supporting other ORMs.

**Comment by rafaelfranca** [comment]
Here is the why https://github.com/plataformatec/devise/pull/4140. It is not that hard to find it since it was linked in the changelog. I know you may be frustrated but please let's keep the discussion in a proper tone.

I do agree we should not be using a method that is not implemented by others ORMs but this change is to improve security given that with active record or sequel (since it also show all values of a model in its `#inspect` implementation) your users passwords can be sent to external service.

Given that this problem is also present when you use sequel and that sequel is not one of the officially supported ORMs should devise-sequel reimplement this method as it does with many other devise internal methods?

Which suggestion do you give so we can improve the sequel support but also fix this problem that is also present if you use sequel?

**Comment by rosenfeld** [comment]
I understand the reasoning about this change and even implemented some fix in master of sequel-devise which I intend to release once Tiago reviews it and think that's acceptable:

https://github.com/rosenfeld/sequel-devise/commit/a916ef5127c0073334ec1543952f12137755cd3d

I'm just not sure whether such concerns belong to Devise's domain. If I understand the problem correctly, it seems some might be worried  that some sensitive information goes to NewRelic or any other service or through e-mail using some gem like exception_notifier and so on. But in that case, even applications which are not using Devise would suffer from the same issue. That's why I think that maybe it should be handled in another place. I'm not complaining or upset/frustrated while commenting this though. It's just that I'm not sure that such security concerns would belong to an authentication library...

What is the reason for this issue to be still open? If this is the reason, I'll try to respond:

> should devise-sequel reimplement this method as it does with many other devise internal methods?
> Which suggestion do you give so we can improve the sequel support but also fix this problem that is also present if you use sequel?

Well, sequel-devise has to implement them because they are required by Devise, so I don't think it has another reasonable option actually :)

I'm probably going to move from Devise to some custom authentication code at some point and when that happens it's likely I'll stop supporting sequel-devise and it would be good if someone else was interested in taking over it when that happens. Lack of official support for Sequel is just one of the reasons, but there are others too, but this is outside of the scope of this discussion.

What I'd like to say is that it would be much easier for other ORMs to support Devise if Devise was fully compatible with orm_adapter and whenever they need more methods from the ORM they would also add to the `orm_adapter` and increase its version. This way, if sequel-devise implements version 1.0 of `orm_adapter` it can be released by requiring orm_adapter 1.0. If Devise needs yet another new method, it would add it to orm_adapter (or devise_adapter, whatever) and increase the version number. This way, someone trying to use latest Devise with latest sequel-devise wouldn't be able to because Bundler would tell them they are incompatible. Also, it would be much simpler for sequel-devise to know what is missing in the new devise_adapter gem version without having to dig into Devise's source code. But anyway, this is just a suggestion as I'm probably moving from Devise even if that happens because, as I said, there are other reasons why I think it would be simpler to use some custom code for my particular application. But in case someone is interested on maintaining a gem to support Sequel with Devise (or any other ORM), it would be very helpful if such devise_adapter gem existed.

Cheers.

**Comment by TiagoCardoso1983** [comment]
@rafaelfranca not to be taken as a slight, I just found the patch at the #inspect level very hopeful. The #serializable_hash method seems important, but that #super call leaves me wondering what is the spec that devise follows for orms.

The question here is, what should devise control. @rrosenfeld already mentioned orm_adapter, and this should be the guideline for devise, but we could safely assume that activemodel could become a reasonable spec (which sequel already supports). The other thing is the attributes that devise knows explicitly from the user model (p.ex. email, encrypted_password) and could use/filter out in a possible inspect implementation. So, devise could implement #inspect with the known parameters and the api supported my activemodel spec/ orm_adapter.

I will look at this further during the week, I'm currently not at my laptop and can't go more into detail for now.

**Comment by lucasmazza** [comment]
> The #serializable_hash method seems important, but that #super call leaves me wondering what is the spec that devise follows for orms.

`serializable_hash` comes from `ActiveModel::Serialization`. ActiveModel ends up being the base API for instance level behavior that devise expects from models, while `orm_adapter` abstracts only the querying APIs between different ORMs - which is were the gap between libraries like AR, Mongoid and Sequel is expected to be bigger, and I believe that pushing the burden of normalizing more methods into it seems to be outside of `orm_adapter` [goals](https://github.com/ianwhite/orm_adapter#goals):

> ORM Adapter's goal is to support a minimum API used by most of the plugins that needs agnosticism beyond Active Model.
>
> ORM Adapter will support only basic methods, as get, find_first, create! and so forth. It is not ORM Adapter's goal to support different query constructions, handle table joins, etc.

We would love to help out on improving the integration with other ORMs like sequel, but bear in mind that we can't cover all corners by ourselves - maintenance of bridge gems like `sequel-devise` will always be required, so would be awesome to have someone who cares about it to keep an eye on this repo activity and help with keeping the integration between gems in check :)

I'm closing this one as the `sequel-devise` patch has been released - thanks @rosenfeld por pushing it. Let's discuss further improvements to ORM support in different threads.

**Comment by TiagoCardoso1983** [comment]
> serializable_hash comes from ActiveModel::Serialization. ActiveModel ends up being the base API for > instance level behavior that devise expects from models, while orm_adapter abstracts only the querying > APIs between different ORMs...

querying yes, persistence not so much. ```orm_adapter``` stabilized 2 years ago and the support provided in ```sequel-devise``` seems good enough. About the ActiveModel being the expected API level, [I opened an issue recently in sequel](https://github.com/jeremyevans/sequel/issues/1201) where the author redirects me [here](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/lint.rb) as the basis of the activemodel plugin. Seems the base API has been formalized there. Sadly it doesn't formalize persistence/serialization, and this is where devise becomes opinionated, like [here](https://github.com/plataformatec/devise/blob/master/lib/devise/models/confirmable.rb#L47-L53). 

These are some suggestions from the top of my head:

* Model security concerns should be out of devise's scope. ORMs should take care of it, and concerns could be "out-sourced" to ```activerecord```, where an API could be formalized to not expose certain parameters (like [this one for logging parameters](http://edgeguides.rubyonrails.org/action_controller_overview.html#parameters-filtering)). @rafaelfranca , how would you feel about this? 
* Model APIs could (maybe) be formalized so that gems like ```sequel-devise``` (or even ```sequel```) could better comply. Something like saying that the following ActiveModel APIs (ex: errors, dirty, validations, serialization...) need to be implemented at the model level (authenticatable and database_authenticatable seem to be the core points of these APIs) for full devise core compatibility. 

I don't know how feasible could this be done, and you could best tell me whether this is worth opening new threads. I've been following devise almost since the beginning, and I don't take your support for granted. It's quite feature-rich and supporting different APIs in such a scenario is obviously hard. So my apologies if it might have sounded harsh, it was probably just another friday in planet Earth :)
