### ISSUE TITLE
Can someone write a document about how devise work?

### ISSUE THREAD

**Issue by 1c7** [plataformatec/devise#4235]
where all these code?
by default, the devise controller and devise  view code doesn't exist in Rails project folder, 
so must be somewhere else, but where?

and why write stuff like this in routes.rb and it work?
```
devise_for :users, skip: [:sessions, :registrations]
```

I would like to see a tutorial that explain how devise work in bigger picture.
Thanks :smile:

**Comment by JPrevost** [comment]
Devise is an engine, so that stuff is hidden in the gem.
More on Engines: http://guides.rubyonrails.org/engines.html

More on how to generate views into your application to modify:
http://devise.plataformatec.com.br/#configuring-views

More on how the routes work that:
http://devise.plataformatec.com.br/#configuring-routes


This tip may also be useful depending no your background:
http://devise.plataformatec.com.br/#starting-with-rails

**Comment by 1c7** [comment]
Thank you very much! @JPrevost

**Comment by lucasmazza** [comment]
There is also a talk from Windy City Rails 2014 with some extra details on Devise internals http://afterhours.io/talks/devise-en.html :)

**Comment by 1c7** [comment]
@lucasmazza Thank you!
