### ISSUE TITLE
duplicate of https://github.com/plataformatec/devise/issues/471

### ISSUE THREAD

**Issue by paulgrant999** [plataformatec/devise#4289]
it four years later, and I got bit by the same bug.  took me 3-4 hours of looking to figure out how to even find the terminology to locate the issue.

figure out some way to monkey patch current_page? so that it doesn't mangle the scope for your controllers on uri generation using the old syntax.  OR POST HERE, how to do it.   problem is:

devise install.

application.html.erb

unless (current_page?(:controller => "blah", : action => "blah2")) 
do some shit
end

breaks, as soon as it hits the devise controllers.  but the stack trace, error message don't have anything to do with devise.  instead it mangles it, and pops up an error on current_page, with a "devise/blah", :action "blah2" URI generation error.  WHICH IS A BITCH, to debug. 

...

so the problem is, current_page? with old controller syntax is inserting devise/ in front of calls to current_page?(:controller => "soome controller", :action => "some action").   THe solution had absolutely nothing to do with devise files, route selection/creation or any of that garbage.   The solution, was to explicitly call the URI_generating path.   in this case, change:

current_page?(:controller...:action....) to:
current_page?(blah_blah2_path);

thats, what fixes the retarded scoping issue, for current_page? // devise.

I look forward to some insightful commentary, on why this is happening.  How does "devise/"?  and how can I monkey patch current_page?  other than literally writing a wrapper/test/mixin?  

On the plus side, now I know that URI generation craps out on the older style :controller=> action=> syntax. :)  which makes me wonder, is their a :scope variable I'm supposed to be supplying?

**Comment by naterexw** [comment]
+1

**Comment by tegon** [comment]
Hello, thanks for your report.
I think there's some confusion here, I'll try to explain:
First, @naterexw, there's no `index` action for `Devise::SessionsController`, that's why you're getting the error you mentioned above.

About the `current_page?` helper, [it tries to generate a URL](https://github.com/rails/rails/blob/2135daf0d552bbb2eca4208f8c33fb015cf052ab/actionview/lib/action_view/helpers/url_helper.rb#L546) based on the `controller` and `action` options by calling the `url_for` helper, which prepends the current controller namespace in order to generate the routes. 

Since Devise use namespaced controllers, if you access a Devise page, `url_for` will try to automatically prepend `devise/` to the `controller` option. You can fix this by adding a forward slash to the `controller` option or by using the route path helper, as you mentioned above.

For example, I've created a simple Rails application with Devise, and a `Game` resource:
```rb
# routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :games
end
```
Added a `byebug` call in my layout:
```erb
# app/views/layouts/application.html.erb
<%- byebug %>
```

When I access a Devise route, for example `/users/sign_in`:
```rb
(byebug) url_for(controller: 'games', action: 'show')
(byebug) *** ActionController::UrlGenerationError Exception: No route matches {:action=>"show", :controller=>"devise/games"}
nil
```
This happens because the current route is on the `devise` controller namespace. However, if I add the slash, it works properly:
```rb
(byebug) url_for(controller: '/games', action: 'show')
"/games"
```

This doesn't happen if we aren't inside a Devise route. For example, if I access `/games`:
```rb
(byebug) url_for(controller: 'games', action: 'index')
"/games"
```
In order to generate a `devise` route here, I have to manually include the `devise` prefix, since this controller is not on the `devise` namespace:
```rb
(byebug) url_for(controller: 'sessions', action: 'create')
*** ActionController::UrlGenerationError Exception: No route matches {:action=>"create", :controller=>"sessions"}
nil
(byebug) url_for(controller: 'devise/sessions', action: 'create')
"/users/sign_in"
```

I hope this clarifies what's happening here. This is a behavior from the Rails URL helpers, not something we added to the Devise gem. 

Thank you!
