### ISSUE TITLE
Unable to authenticate devise user with Imap

### ISSUE THREAD

**Issue by JohnMerlino1** [plataformatec/devise#4301]
I am using devise in my application. And I am trying to authenticate the user with Imap but the way devise is storing the password, it just doesn't work:

```
> imap = Net::IMAP.new('imap.gmail.com',993,true)
> imap.login(user.email, user.password)
> Net::IMAP::BadResponseError: Invalid arguments supplied to LOGIN. 

> imap.login(user.email, user.encrypted_password)
> Net::IMAP::NoResponseError:  Invalid credentials (Failure)
```
How am I supposed to validate this user's password?

**Comment by Shwetakale** [comment]
@JohnMerlino1 Devise stores md5 digest of password and as far as I know there is no way from which you can get original password from md5 digest. Imap requires original password not encrypted so I think you will have to store original password in some other field by using your own encryption using JWT or any other preferred algo. Hope this helps.

BDW Why are you storing user's password in your database instead of using google oauth (Google Api's) ? I would like to know such usecase.

**Comment by nashby** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
