### ISSUE TITLE
Need to create `users` table before `$ rails generate devise:install` ?

### ISSUE THREAD

**Issue by itsNikolay** [plataformatec/devise#4312]
```shell
❯ rake db:migrate
== 20161001202910 AddDeviseToUsers: migrating =================================
-- change_table(:users)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "users" does not exist
: ALTER TABLE "users" ADD "email" character varying DEFAULT '' NOT NULL
/db/migrate/20161001202910_add_devise_to_users.rb:5:in `block in up'
/db/migrate/20161001202910_add_devise_to_users.rb:3:in `up'
-e:1:in `<main>'
```
- master branch (version: 4.2.0, revision: 88724e10adaf9ffd1d8dbfbaadda2b9d40de756a)
- Rails 5.0.0.1

I fixed it by creating a `users` table in database

**Comment by nashby** [comment]
@itsNikolay hey, looks like you created `User` model but didn't run migration that creates users table. There's some logic about that here https://github.com/plataformatec/devise/blob/master/lib/generators/active_record/devise_generator.rb#L13. Closing it since it shouldn't be an issue if everything's created in right order.
