### ISSUE TITLE
Readme for controller testing is out of date?

### ISSUE THREAD

**Issue by jeremyawhitman** [plataformatec/devise#4369]
According to the Readme section on controller testing:

> Controller tests require that you include Devise::Test::ControllerHelpers on your test case or its parent ActionController::TestCase superclass.

```
class PostsControllerTest < ActionController::TestCase
  include Devise::Test::ControllerHelpers
end
```

I do not think that is correct with Rails 5, as newsly generated controller tests now look like this: 
class PostsControllerTest < < ActionDispatch::IntegrationTest
end

and to be able to log in a test user I must not use   include **Devise::Test::ControllerHelpers** but  **include Devise::Test::IntegrationHelpers**  does work if I include it on the controller.

```
 class PostsControllerTest < < ActionDispatch::IntegrationTest
   include Devise::Test::IntegrationHelpers 
 end

```
Am I correct that the documentation is currently wrong, or have a missed something?

**Comment by Sathors** [comment]
I have the same conclusion than you. Actually, I think that Rails by default now only uses IntegrationTests, right?

**Comment by tegon** [comment]
Hello @jeremyawhitman, thanks for your report.
The controller tests were moved out from Rails 5 to the [rails-controller-testing](https://github.com/rails/rails-controller-testing) gem. That's why they haven't  been generated anymore with scaffold. But the information can still be relevant to people that are using controller tests in their app.
The code you mentioned is for integration tests, which are also in our [README](https://github.com/plataformatec/devise#integration-tests).

**Comment by foucist** [comment]
Holy smokes.  I totally missed the ` For Rails 5, include Devise::Test::IntegrationHelpers instead `  part.. reading comprehension fail 😅
