### ISSUE TITLE
Different sign_in_after_reset_password values for different resources

### ISSUE THREAD

**Issue by roshats** [plataformatec/devise#4378]
I have two models: User and AdminUser. I want a user to be signed in after reseting password but not admin. How can I do this? This behavior is defined by one configuration option now: https://github.com/plataformatec/devise/blob/8a4d610/app/controllers/devise/passwords_controller.rb#L37 .

**Comment by tegon** [comment]
Hello @roshats, thanks for your report.
This is indeed a global option. We haven't plans on supporting this for now, so although I know it's not ideal, you probably will have to override this action in order to add your custom behavior.
If this became a popular feature request we can think about supporting in a next major version.

Thank you!
