### ISSUE TITLE
Failed to login with devise

### ISSUE THREAD

**Issue by vishnurkrishnan** [plataformatec/devise#4414]
I am using devise gem for authentication, current rails version is 3.2.22, so my password have some special character like 'admin@123' , after upgrade to ruby 2.2.0 i couldn't login with that credentials but that allows me to login after removing that '@', also 'password@123' is working.

current version which am using

devise (2.2.1)
      bcrypt-ruby (3.0.1)
      orm_adapter (~> 0.1)
      railties (~> 3.1)
      warden (~> 1.2.1)

**Comment by georgeguimaraes** [comment]
I'm sorry, but devise 2.2.1 was released more than 4 years ago.
I won't be able to help you with that, since it's not clear this is an issue in Devise (and because that version is too old to be maintained).

Best help I can do is to direct you to Stack Overflow for help, where a wider community may be able to help  Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
