### ISSUE TITLE
Any way to set :authenticated_root for multiple user classes (Agent & Admin)

### ISSUE THREAD

**Issue by jpwynn** [plataformatec/devise#4424]
I was hoping something like `authenticated [:admin, :agent] do` would allow setting :authenticated_root if any of multiple types are signed in. Is there a way to do something like that?

If using multiple user types, Admin and Agent, Rails 5 will not permit :authenticated_root to occur more than once in routes.rb.

Specifically, "Invalid route name, already in use: 'authenticated_root'" is raised when you try this:

    authenticated :admin do
       root 'pages#admin_home', as: :authenticated_root
    end
    authenticated :agent do  
       root 'pages#agent_home', as: :authenticated_root # THIS RAISES EXCEPTION
    end

So I tried creating a new action pages#authenticated_home that does a redirect based on which type of user is sign in, with first priority to Admin, like this:

    def authenticated_home
      redirect_to admin_home_path and return if current_admin
      redirect_to agent_home_path and return if current_agent
      redirect_to home_path
    end

But I cannot figure out if it is possible to use 'authenticate' in routes.rb and specify multiple user types, for example this does not work (no exception, but it gets ignored and default root route is used whetherAdmin or Agent (or both) are signed in).

    authenticated [:admin, :agent] do  # THIS GETS IGNORED
      root 'pages#authenticated_home', as: :authenticated_root
    end

If not currently supported, perhaps this is a worthwhile feature to extend `authenticated` or introduce something like `authenticated_any` ?

**Comment by tegon** [comment]
@jpwynn We call Warden's `authenticated?` method [directly](https://github.com/plataformatec/devise/blob/f39c6fd92774cb66f96f546d8d5e8281542b4e78/lib/devise/rails/routes.rb#L480), which only accepts one scope.
I guess we could try to authenticate with multiple scopes by calling `warden#authenticated?` multiple times, but since Warden itself doesn't support this, it seems a bit hacky.
What you did with your `authenticated_home` action is the way to go, I think.
