### ISSUE TITLE
SMTP provider clicking links and confirming accounts

### ISSUE THREAD

**Issue by mbulat** [plataformatec/devise#4440]
We've noticed that SparkPost often clicks links in emails, presumably to check for spam or something. This is causing accounts to get confirmed automatically when the email goes out. I found this issue also effecting gitlab-ce https://gitlab.com/gitlab-org/gitlab-ce/issues/3048

I understand that it's possible to override the behavior, and that's what we are doing now. I'm not sure how prevalent it is for SMTP providers to be clicking links on outgoing email, but if it is common, perhaps this is an under reported issue. We didn't notice it until we were inspecting the logs closely. 

The fact that devise is doing an update on the user via a GET request may break other systems that assume GET requests to be safe.

**Comment by tegon** [comment]
Hello @mbulat, thank you for the report.

> The fact that devise is doing an update on the user via a GET request may break other systems that assume GET requests to be safe.

The confirmation email has to work with GET requests because that's the only HTTP method supported on browser links.

I never heard of this before, I don't think it's very common.  That's the reason I'm going to close this issue, but if more people struggle with this we can reopen the discussion.

Thank you!
