### ISSUE TITLE
Rails 5 orm not loaded error

### ISSUE THREAD

**Issue by jailalawat** [plataformatec/devise#4467]
I am using Ruby 2.3.1 and rails 5.0.2, I am install devise 4.2.0
and generate the 2 model Admin and User, everything is working fine but some time it will give us me following error when i click on signout or any other validation occur

User does not respond to 'devise' method. This usually means you haven't loaded your ORM file or it's being loaded too late. To fix it, be sure to require 'devise/orm/YOUR_ORM' inside 'config/initializers/devise.rb' or before your application definition in 'config/application.rb'

Here is my routes.rb 

```ruby
devise_for :users
  devise_for :admins
  namespace :admin do
         resources :users do 
	  	member do
	  		post :campaigns
	  	end
	  end 
  end
```

```ruby
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

class Admin < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
end
```

in devise.rb

```ruby
require 'devise/orm/active_record'
```

**Comment by carlosantoniodasilva** [comment]
Can you please provide a sample application that reproduces the issue? Thanks.

**Comment by jailalawat** [comment]
Hi Thanks for the reply

Here is sample app https://github.com/jailalawat/devise_error_app

I got a new error when you try to login 
http://localhost:3000/admins/sign_in

admin@admin.com and try to put a wrong password like 12345678902


NoMethodError in Devise::SessionsController#create
undefined method `failed_attempts' for #<Admin:0x007f973c5d22c8>

**Comment by carlosantoniodasilva** [comment]
@jailalawat the error you mention on your last comment seems different from the one you opened the issue with. Let's focus on the last comment now since that's what is happening with your app:

It appears your [Admin model enabled the `lockable` module](https://github.com/jailalawat/devise_error_app/blob/master/app/models/admin.rb#L5), which by default will lock the user account after a number of failed attempts to sign in. However, your [devise migration doesn't seem to contain the lockable field](https://github.com/jailalawat/devise_error_app/blob/master/db/migrate/20170307101125_devise_create_admins.rb#L29), since it's commented out, which means your admins table do not have the `failed_attempts` field, causing devise to error when trying to access/write to that field after a wrong sign in attempt.

To resolve that, you should either add the field to your admins table, or remove the lockable module from your model if you're not going to use this functionality.

I hope that helps, let us know if you hit any other issue.

**Comment by kevinhq** [comment]
I had the same error but it's not always happening, and only happened on development. Restarting the server fixed it.

**Comment by deekshithh** [comment]
I am using Rails 5.2 && ruby 2.6.0.
Adding `extend Devise::Models` in the User Model, helped me solve the issue.
