### ISSUE TITLE
Validate password in Devise::Models::Recoverable#reset_password

### ISSUE THREAD

**Issue by michiomochi** [plataformatec/devise#4473]
Related: 
https://github.com/plataformatec/devise/pull/4456
https://github.com/plataformatec/devise/compare/v4.2.0...v4.2.1#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR7

I think that definition of validation should write on validate clause in model. and, Password validation is defined in the following code.
https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/lib/devise/models/validatable.rb#L33

Why need a password validation in `Devise::Models::Recoverable#reset_password`?
I think don't need password validation in `Devise::Models::Recoverable#reset_password`.

**Comment by carlosantoniodasilva** [comment]
The password is not validated when it's `nil`, as you can see in [`password_required?`](https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/lib/devise/models/validatable.rb#L54). This means that if no password is provided within the reset password request, the request would succeed without actually performing the password change, and we want it to fail - because you're resetting your password.

Please check #4397 for more information. If you have more thoughts on why it should be different, we'll be happy to reopen and discuss. Thanks!
