### ISSUE TITLE
Default installation crashes tests

### ISSUE THREAD

**Issue by mattisfrommars** [plataformatec/devise#4475]
By following the instructions from the Readme on a rails 5.0 project created with `rails new myapp`, you end up with the following error:
```
Error:
HomeControllerTest#test_should_get_index:
ActiveRecord::RecordNotUnique: SQLite3::ConstraintException: UNIQUE constraint failed: admins.email: INSERT INTO "admins" ("created_at", "updated_at", "id") VALUES ('2017-03-23 16:00:12.355353', '2017-03-23 16:00:12.355353', 298486374)
```

This can be fixed by removing the admins.yml (or whatever you called your model), but it's not immediately obvious that that's how to fix it. Or at least it wasn't to me, given my limited experience with rails.

**Comment by eldano** [comment]
I agree that the default installation shouldn't break the tests. This is because the fixture being created is the default rails fixture which creates two entities without any attributes, and that means two users/admins/whatever with same email (nil).
The minimum change to make the tests pass is to remove the second user from the fixture. I think Devise should provide a fixture like that by default.

**Comment by tegon** [comment]
Hello, @mattisfrommars I understand your frustration but Devise doesn't generate those fixtures, we only call your application's [active record generator](https://github.com/eldano/devise/blob/master/lib/generators/active_record/devise_generator.rb#L21) - this means that Rails itself is creating those fixtures.
We could accept a patch like the one sent by @eldano, but I think we shouldn't because a lot of people use factories in their project and not fixtures.
By only calling the application generator, we ensure that it can work distinct environments.

Thank you!
