### ISSUE TITLE
Devise currently does not have a customizable redirect helper upon authentication failure

### ISSUE THREAD

**Issue by NuclearMachine** [plataformatec/devise#4500]
We have helpers to redirect upon success such as `after_sign_up_path_for` and `after_inactive_sign_up_path_for` but we currently do not have any helpers when a signup/login fails. Solutions online such as [this](http://stackoverflow.com/questions/5832631/devise-redirect-after-login-fail) works but very limited in scope and sometimes buggy.

**Comment by tegon** [comment]
Hello @NuclearMachine, thanks for your request.
We don't have plans to support this for now, so although I know it's not ideal you probably will have to override this code in order to add your custom behavior.
If this became a popular feature request we can think about supporting in a next version.

Thank you!
