### ISSUE TITLE
Timeoutable redraw page  / ping keeps alive

### ISSUE THREAD

**Issue by grimmwerks** [plataformatec/devise#4521]
Hey all; in part of that whole hippa thing we can't have data staying on screen once someone times out; right now a user times out but their screen can remain on screen with patient data.  I thought I'd be clever (and we'll see where that goes) and create a ping that would return a 401 when the user was timed out; thing is since it's pinging the server every minute it's keeping the connection alive.

Is there a way that timeoutable can redraw to the sign in?  Do I have a timer or job running that checks if the current user timed out?

**Comment by rafaelfranca** [comment]
Hi @grimmwerks thank you for the issue. Since this is more a question than an issue I recommend you to ask in a different channel like Stack Overflow where more people can help you.

Answering your question quickily, no, there is no way to devise send information to the client browser without a request to be made. And no, there is no timer running. What timeoutable does is check if the session was expired in the next request. If no request is made the page is still there.
