### ISSUE TITLE
rails vs rake command inside the documentation page

### ISSUE THREAD

**Issue by giacomo-giovenzana** [plataformatec/devise#4534]
First time on Rails framework.
Reading the documentation here: https://github.com/plataformatec/devise, in the paragraph "Getting started", after the command "$ rails generate devise MODEL" there is the step "rails db:migrate". I have experimented that the command is not "rails db:migrate", but it is "rake db:migrate" (I am using rails  4.2.1).
Replace "rails" with "rake".

**Comment by Deckluhm** [comment]
Just so you know, since Rails 5 you can use `rails` instead of `rake` (there used to be some commands using `rake` and some other using `rails`, it is now unified).

Since Rails 5 is pretty new, it's probably a good idea to add a note about `rake`/`rails`.

Just a question: why using Rails 4.2 if you are starting with Rails?

**Comment by giacomo-giovenzana** [comment]
I am using ruby 4.2 because I am following a course on that and because I have installed tokaido app which has 4.2. It is only for starting to play with rails. Sooner I will pass to version 5.

I think we can close the issue. Thanks.
