### ISSUE TITLE
Error message `last attemps` on Rails 5.1.2 not appear

### ISSUE THREAD

**Issue by maengkom** [plataformatec/devise#4583]
I am new in rails and gem devise, and create new rails app version 5.1.2 and add gem devise then install it, configure using guidelines, then I can login. After that I tried to login using wrong password, not show login error message, but last attempt error message not shown. Here's my sample code.

```
# config/initializer/devise.rb

config.lock_strategy = :failed_attempts
config.maximum_attempts = 3
config.last_attempt_warning = true

# user.rb model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
end

# users.rb migration file

      ## Lockable
      t.integer  :failed_attempts, default: 0, null: false # Only if lock strategy is :failed_attempts
      t.string   :unlock_token # Only if unlock strategy is :email or :both
      t.datetime :locked_at
```

trying 2 times, then `failed_attemps` fields in table `users` contain 2 as value. But warning last attemp not appear. Also wrong password do not have error message, perhaps this is by design ?

**Comment by tegon** [comment]
Hi @maengkom, thanks for your report.
In order to show the messages, you have to render them in your layout, like this:
```erb
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
```

Check the documentation for more information about it: http://api.rubyonrails.org/classes/ActionDispatch/Flash.html

Please use StackOverflow for questions like this one in the future. There a wider community will be able to help you. 

We reserve the issues tracker for issues only. Thank you!
