### ISSUE TITLE
Trackable should be invoked on sign in, not on authentication

### ISSUE THREAD

**Issue by waiting-for-dev** [plataformatec/devise#4584]
Hi,

I'm the developer of [devise-jwt](https://github.com/waiting-for-dev/devise-jwt). This gem provides with a warden strategy which authenticates a user if a valid JWT token is present in request headers.

Recently, a user came in with a pull request so that when devise-jwt strategy is used to authenticate a user trackable information is not updated (https://github.com/waiting-for-dev/devise-jwt/pull/23).

After studying it, I came to the conclusion that it is something that should be fixed from devise end.

Right now, [trackable behaviour is invoked from a warden `after_set_user` hook](https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/lib/devise/hooks/trackable.rb). I think it is not correct. `update_tracked_fields!` should be invoked from the warden strategies that are meant to be used during a sign in, that is, from [database_authenticatable](https://github.com/plataformatec/devise/blob/master/lib/devise/strategies/database_authenticatable.rb). Warden strategies which are not used to sign in, like providing a token obtained during an actual sign in, should not be affected.

I think changing this should be very easy. We should just add one line of code to the validated user block in database_authenticatable strategy. I could prepare a pull request, but I would like to know beforehand whether it will be accepted or whether you think this could have some backward incompatibility issue I can't imagine right now.

Thanks!

**Comment by joshkinabrew** [comment]
Bump.

Running in to this today, I was trying to figure out why my user was signed in 156 times even though the user was created only 5 minutes ago. Turns out each request updates the user sign in count. Would love to see this fixed one way or another.

**Comment by mariuszmikolajczak** [comment]
Bump.

Any chances to look in to it?

**Comment by tegon** [comment]
Hello @waiting-for-dev, thanks for digging into this.

Looking at the codebase, seems like we would have to update the `sign_in` helper too, since it's calling `#set_user` [directly](https://github.com/plataformatec/devise/blob/d9deeba582b64b75e249f6ecd86768e5a49e22a6/lib/devise/controllers/sign_in_out.rb#L50).

Just to be sure: in your gem the `database_authenticable` strategy will be called first sign in, then only a `token` strategy will be called. Is that correct?

**Comment by waiting-for-dev** [comment]
Hello @tegon , thanks for your repply.

> Looking at the codebase, seems like we would have to update the sign_in helper too, since it's calling #set_user directly.

Right, I missed it.

> Just to be sure: in your gem the database_authenticable strategy will be called first sign in, then only a token strategy will be called. Is that correct?

Yes, that's correct.

**Comment by tegon** [comment]
It makes sense for me to change this, but sadly I can't be sure if this can cause some backward incompatibility because it can be a lot of code out there relying on this behavior.
I'm ok with changing this on a next major version, then the users can be sure that it's a significant change of behavior.
To work with the current version, I guess this can be solved by setting `env['devise.skip_trackable'] = true` in your strategy, right?

**Comment by waiting-for-dev** [comment]
I understand your backwards compatibility concerns... I don't think that the change would be too drastic, because even if the implementation would change, the end-user functionality would remain the same. But maybe there is some edge cases out there...

The problem is that my gem is built on top of another gem I also developed which works with plain `warden`. The strategy in `devise-jwt` is just reused from that other gem, where it makes no sense to add anything related to `devise`. And I don't want to complicate the devise layer just for that. Surely I will point to the workaround in a wiki page.

By the way, is there an expected release date for `devise` 5.0?

**Comment by tegon** [comment]
I see, and mostly I agree with you that the end-user functionality wouldn't change. Maybe I'm being too defensive on this, but we had problems in the past with strange devise behaviors that we fixed - and thought no one would be relying on them - but it turns out, a lot of people were, without even noticing. 
About version `5.0`, I've created the [milestone](https://github.com/plataformatec/devise/issues?q=is%3Aopen+is%3Aissue+milestone%3A5.0) and there are some features to implement yet, so I don't have a expected release date yet.

**Comment by nicklayb** [comment]
We are currently having this issue, is there any temporary fix you can suggest against this?

**Comment by mopx** [comment]
> We are currently having this issue, is there any temporary fix you can suggest against this?

I had the same problem today, you could disable trackable and add an after_action on the session controller and update the columns yourself.

**Comment by tegon** [comment]
@waiting-for-dev Yep 👍

**Comment by tegon** [comment]
Closed via #4987

**Comment by wengzilla** [comment]
Has this been released? If not, is there a suitable workaround?

**Comment by ackshaey** [comment]
Same question, has this been released? I'm seeing the sign_in_count be updated for every invocation of current_user. Any recommendations or workarounds?

**Comment by ackshaey** [comment]
For anyone else facing this, I used https://github.com/waiting-for-dev/devise-jwt/issues/12#issuecomment-387325935 to fix this. Add the following initializer to skip trackable for `authenticate_!` calls:

```ruby
# https://github.com/waiting-for-dev/devise-jwt/pull/23
# https://github.com/plataformatec/devise/issues/4584

module Devise
  module JWT
    module WardenStrategy
      def authenticate!
        super
        env['devise.skip_trackable'.freeze] = true if self.valid?
      end
    end
  end
end

Warden::JWTAuth::Strategy.prepend Devise::JWT::WardenStrategy
```

**Comment by carlosantoniodasilva** [comment]
Reopening to revisit at some point, see https://github.com/heartcombo/devise/pull/4987#issuecomment-3702606191
