### ISSUE TITLE
Use update_attribute instead save(validate: false)

### ISSUE THREAD

**Issue by myxrome** [plataformatec/devise#4591]
Some ORMs, [Her](https://github.com/remiprev/her) for example, does not support save method with arguments. This is why save(validate: false) will fail the integration with ORM using orm_adapter-*.
Could you please replace save(validate: false) to update_attribute?

**Comment by tegon** [comment]
Hi @myxrome, thanks for your suggestion.
Unfortunately, we may break the current behavior if we change this. Since we save the hole model now, it's very likely that some users are setting different attributes on the model before saving it.
Since we don't support the `Her` ORM, I'm going to close this issue.

Thanks!
