### ISSUE TITLE
80 column limit exceeded in devise.rb initializer

### ISSUE THREAD

**Issue by brunofacca** [plataformatec/devise#4633]
Multiple comments in the devise.rb initializer exceed the 80 column limit. That generates a lot of Rubocop offenses. May I submit a PR to wrap all of the initializer template's comments to 80 columns?

**Comment by tegon** [comment]
Hi, @brunofacca!
Thanks for your suggestion.
IMHO, I don't think we should do that because the column limit may vary from project to project. For instance, I'm working on one that has a 100 column limit.
But after you installed Devise, you can edit the initializer to match your limit, or you can also configure Rubocop to ignore this file since it's not your application code.

Thanks again for your interest to contribute with Devise.
