### ISSUE TITLE
Lockable Failed Attempts Never Expire

### ISSUE THREAD

**Issue by LenPayne** [plataformatec/devise#4679]
I've been asked to modify our login procedure so that failed attempts eventually expire. For example, we have the lockout strategy set for 3 failed attempts, and the unlock strategy for both 1hr or e-mail.

But the use-case we have is that people are putting in two failed attempts, giving up, trying again the next day, and failing: bam, that's their third attempt and they're immediately locked out. Even though more time than the unlock strategy has past.

I'd like to add an optional `last_attempt_at` datetime field to the user model, and when checking for failed attempts, if the `config.unlock_strategy` is set to `time` or `both` AND the `last_attempt_at` was more than the `config.unlock_in` time, it should reset the `failed_attempts` before continuing.

Is this change desirable? Does it seem like a good idea? Or shall I go back to shoe-horning the behaviour in my own app?

**Comment by tegon** [comment]
@LenPayne I understand your use case, you actually need a different behavior.
You want to unlock the account with the time **before** it was locked by the maximum failed attempts.
Since this seems like a really specific requirement, I don't think we should support it for now.
While I know it's not ideal, I think the best path for you now is to implement this in your app.

I hope you get my point. Thank you!

**Comment by craigbrott** [comment]
I also need an expiring failed attempt counter. Failed attempt tracking seems pretty useless without a counter expiry. 

Imagine a regular user who makes a typo signing in about once a month. If you allow a maximum of 6 failed sign-in attempts attempts, after 6 months they will be locked out for no real reason and the user will be very confused.

The point of a locking mechanism like this is to prevent an unauthorized person from brute forcing their way into someone else's account, not to punish a user for occasional typos.

A quick fix that doesn't require any changes to Devise code is a cron job that runs at a specified time interval that decrements the failed attempts counter by 1, until reaching 0. For example, if you want to lock the account after 6 failed sign-in attempts within 1 hour, you can decrement the count by 1 every 10 minutes.

**Comment by LenPayne** [comment]
Actually, I built it and we've been using it internally for eight months.

https://github.com/LenPayne/devise/commit/3558dbb60e72323fd677bc4f764c199b986a4786

This was originally forked off of 3-stable.

**Comment by mkarklinsScout** [comment]
@LenPayne do you have any plans adding a PR with that change to upstream Devise?

**Comment by nyanpasu** [comment]
This would be nice to have in Devise. As it is now, the current behaviour is very confusing for most users. Are there any plans to add this in? Or at the very least, have the sign in attempts reset upon logging in?

**Comment by LenPayne** [comment]
We're still using it in production. Based on my comment above, looks like we turned it on Jan 2018 or so. I have an updated fork from 4.5.0: https://github.com/LenPayne/devise/tree/expire_failed_4.5.0

As the initial idea was shot down, I've never reopened the issue or PR, but it works and has done the job.

The individual commit can be dropped on top of most current branches: https://github.com/LenPayne/devise/commit/16eefb099176e1fe049525058de5a7d037b4b38c

**Comment by unikitty37** [comment]
I've just been given a ticket to implement lockout on multiple failed attempts in our app (which uses Devise) and the requirement is for the lockout to occur if there is a given number of failures _within a specific time period_. I can't see Devise's default behaviour being accepted by our users.

I'm not sure building our own custom fork of Devise would be accepted by management. Is there a way to get Devise to do this _without_ having to do that?

(I was also somewhat surprised to see that a successful login doesn't reset the counter. Again, that wouldn't be accepted by our users. I guess we need to call `reset_failed_attempts!` on a successful login, but I would have thought that Devise would do that as a matter of course…)

**Comment by carlosantoniodasilva** [comment]
@unikitty37 

> I was also somewhat surprised to see that a successful login doesn't reset the counter.

A successful login should reset failed attempts, otherwise the behavior is really inconsistent and things like this that was mentioned above could happen:

> Imagine a regular user who makes a typo signing in about once a month. If you allow a maximum of 6 failed sign-in attempts attempts, after 6 months they will be locked out for no real reason and the user will be very confused.

Here's the code that handles resetting whenever there's an explicit user sign in: https://github.com/heartcombo/devise/blob/7d1dc56fdba2402c452c4224567077b23184637e/lib/devise/hooks/lockable.rb#L5-L9

If that is for some reason not working, let me know and we can look into it more, as I'd consider it a bug.

> I'm not sure building our own custom fork of Devise would be accepted by management. Is there a way to get Devise to do this without having to do that?

You don't really need a fork, you can customize some of the behavior with hooks and methods on your own app.

For example, off the top of my head, maybe something like this could work: you can add a timestamp to track it, something like `last_failed_attempt_at`, then override `increment_failed_attempts` https://github.com/heartcombo/devise/blob/7d1dc56fdba2402c452c4224567077b23184637e/lib/devise/models/lockable.rb#L122 and update that timestamp, or reset the counter if it's after your threshold.

```ruby
# pseudo code, untested
def increment_failed_attempts
  if last_failed_attempt_at && last_failed_attempt_at < self.class.unlock_in.ago # or use your own time period here
    # reset failed attempts after a certain threshold
    self.failed_attempts = 0
  end
  self.last_failed_attempt_at = Time.current
  super
end
```

Again this is totally untested, but something that can get you started. I'm not sure if that's behavior to add to Devise just yet, but if something like this is simple enough for your needs and works, maybe we could consider it. I just want to reinforce that resetting failed attempts when successfully logging in should be happening via Devise.

**Comment by carlosantoniodasilva** [comment]
@unikitty37 you should be able to implement that method directly on your model (i.e. `User`), and call `super`, no need to reopen the original module.

```ruby
class User < ApplicationRecord
  # stuff here.

  # devise override
  def increment_failed_attempts
    Rails.logger.info "SUCCESSFULLY PATCHED increment_failed_attempts"

    super
  end
end
```

**Comment by unikitty37** [comment]
@carlosantoniodasilva Thanks! Looks like I was trying to be too clever.

Once I get it working I can add the code to the [documentation in the wiki](https://github.com/heartcombo/devise/wiki/How-To:-Add-:lockable-to-Users), if that would help others.

**Comment by carlosantoniodasilva** [comment]
@unikitty37 sure thing. Maybe a new wiki page might be better though, to keep it specific to the modification you're making.
