### ISSUE TITLE
Allow user to login with unconfirmed_email when using reconfirmable and allow_unconfirmed_access_for set

### ISSUE THREAD

**Issue by koljaa** [plataformatec/devise#4693]
When a user changes his email then the new email is stored in unconfirmed_email. However i want to allow the user to login using the unconfirmed_email for a certain time. How is that possible?

**Comment by tegon** [comment]
I'm afraid you'll have to override some of the login methods to suit your use case.

Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
Thank you!

**Comment by rnestler** [comment]
I hope it's OK if I bump this old issue. I also ran into this and was quite surprised by the behaviour, since `reconfirmable` basically breaks `allow_unconfirmed_access_for`.

I figured I could override `find_for_database_authentication` in my model:
```ruby
  def self.find_for_database_authentication(tainted_conditions)
    super(tainted_conditions) || super({ unconfirmed_email: tainted_conditions[:email] })
  end
```

Is this something one can do or is this likely to break something?
