### ISSUE TITLE
4.4.0 prevents successful logins

### ISSUE THREAD

**Issue by johnmichaelbradley** [plataformatec/devise#4744]
## Environment

- Ruby 2.4.2 and 2.5.0
- Rails 5.1.4
- Devise 4.4.0

I am testing out Ruby 2.5.0 with one of my apps. Since I upgraded to Devise 4.4.0, authorization appears to be broken. Using correct credentials, it appears that the corresponding user account is found (FYI, I am using devise_ldap_authenticatable version 0.8.5) and sign_in_count is incremented, but the browser is sent 401, and the user is asked to log in again. I am able to successfully log in after reverting to Ruby 2.4.2 and Devise 4.3.0.

Thanks for your help.

**Comment by tegon** [comment]
Hello @johnmichaelbradley, thanks for your report.
Can you provide us a sample application that reproduces the issue in isolation?
That would help us find the issue.

Thank you!

**Comment by johnmichaelbradley** [comment]
Hi @tegon! I am going to do some more local testing. I just created a fresh Rails app, and I was able to authenticate just fine.

**Comment by ryym** [comment]
Hi, I just run into this issue too. And reverting to 4.3.0 fixed it.
I'll report more details later if possible.

- Ruby 2.4.2
- Rails 5.1.4

**Comment by johnmichaelbradley** [comment]
Thanks, @ryym. I have had to switch my focus to another project.

**Comment by ryym** [comment]
It turned out that this was completely our application's problem, sorry.

In may case, the cause is a model validation added by https://github.com/plataformatec/devise/pull/4674.
Our model had a weird `before_validation` callback and it blocked successful logins.

```ruby
# Our application's model
class User
  before_validation :set_password

  # ...

  # `set_password` sets a new password if `self.password` is empty.
  # Let me skip an explanation why this weird method exists...
  def set_password
    return if password.present?
    random_string = SecureRandom.base64(10)
    self.password = self.password_confirmation = random_string
  end
end
```

Devise 4.4.0 runs model validations at login so this `before_validation` is called while 4.3.0 does not. Therefore if a user logs in:

1. Model validation is fired and `set_password` is called
1. It sets a new password (😱) because `password` is empty at that time
1. The login fails because of password difference
   (A salt check failed at https://github.com/plataformatec/devise/blob/463351922fdafb96c50ba2496c7d0adaa3223283/lib/devise/models/authenticatable.rb#L232)

I fixed this by just removing the `set_password` callback eventually.

@johnmichaelbradley Perhaps the model validation may have something to do with your case too.
If so, I think we can close this issue :)

**Comment by tegon** [comment]
@ryym thanks for debugging this, I appreciate it.
So, it seems like this is a duplicate of #4742, you can also check the comments there too to get some intel.
@johnmichaelbradley Please let us know when you can check your validations and let us know your conclusions.

**Comment by johnmichaelbradley** [comment]
@tegon I will take a look this afternoon!

**Comment by johnmichaelbradley** [comment]
That was the problem. Thank you, @ryym!
