### ISSUE TITLE
Unnecessary callbacks triggering for sign_in and sign_out

### ISSUE THREAD

**Issue by dilkhush** [plataformatec/devise#4760]
Devise is a great gem I am using for several years now, I found this while working with a project.

In this method #forget_me only ignoring the validation but its triggering all the *_save and *_update callbacks so I have to override this method in my user model 
https://github.com/plataformatec/devise/blob/f39c6fd92774cb66f96f546d8d5e8281542b4e78/lib/devise/controllers/rememberable.rb#L30

My #forget_me! method that doesn't call the callbacks:
`  def forget_me!

    return unless persisted?

    user_data = {}

    user_data[:remember_token] = nil if respond_to?(:remember_token)

    user_data[:remember_created_at] = nil if self.class.expire_all_remember_me_on_sign_out

    self.update_columns(user_data) if user_data.present?
end`

In this method #update_tracked_fields! its triggering all the *_save and *_update callbacks so I have to override this method in my user model 

https://github.com/plataformatec/devise/blob/f39c6fd92774cb66f96f546d8d5e8281542b4e78/lib/devise/models/trackable.rb#L33

Override this method using this:

`   def update_tracked_fields!(request)

    old_current, new_current = self.current_sign_in_at, Time.now.utc

    old_current_ip, new_current_ip = self.current_sign_in_ip, request.remote_ip

    new_sign_in_count = self.sign_in_count || 0

    new_sign_in_count += 1

    self.update_columns(last_sign_in_at: (old_current || new_current), current_sign_in_at: new_current, last_sign_in_ip: (old_current_ip || new_current_ip), current_sign_in_ip: new_current_ip, sign_in_count: new_sign_in_count)

  end `

**Comment by tegon** [comment]
Hi @dilkhush, thanks for your report.
Which devise version are you using?

**Comment by dilkhush** [comment]
Hello @tegon, Please find the versions for rails and devise below:
ruby-2.4.1
devise-3.5.10
rails-4.2.9

**Comment by yskkin** [comment]
I think `Trackable` should not validate a model instance from other point of view:
If validation is added to an existing app, existing user can not log in because of new validation failure.

I also override `Trackable#update_tracked_fields!` with `validate: false` to workaround this, but the following test introduced in #4674 expects other otherwise.
https://github.com/plataformatec/devise/blob/bdd6081815ca80705aada4cf77aed3b2a2df71c7/test/models/trackable_test.rb#L44-L51

Is change like this acceptable to merge?

```diff
diff --git a/lib/devise/models/trackable.rb b/lib/devise/models/trackable.rb
index 9a3056e9..938e3298 100644
--- a/lib/devise/models/trackable.rb
+++ b/lib/devise/models/trackable.rb
@@ -32,7 +32,11 @@ module Devise

       def update_tracked_fields!(request)
         update_tracked_fields(request)
-        save
+        if new_record?
+          save
+        else
+          save(validate: false)
+        end
       end
     end
   end
```

**Comment by yskkin** [comment]
Ah, this issue is for callback, not validation. Sorry...

**Comment by dilkhush** [comment]
@yskkin, @tegon 
Yes, this is for callback and validation for both while signin, devise update the last_sign_in_at, current_sign_in_at, last_sign_in_ip, current_sign_in_ip and sign_in_count and all the callbacks for update is triggered and validation perform for the user.
So If we have written N callbacks then N callback will be triggered so this can impact of performance
The only thing I can see here is we may need a new custom callback method like after_sign_path_for in our model to perform any use case.
Same as above for sign out also.

**Comment by tegon** [comment]
@dilkhush We can't use `#update_columns` because it doesn't run validations, which may cause invalid users being registered in the database. See https://github.com/plataformatec/devise/issues/4673 for more information.

It's possible to disable the callbacks, but we need to know which callback we're going to disable, and we need to set it again later. Since Devise is a gem, this doesn't seem like something it should take care of - because it's more related to your code itself.

I guess you can add some conditionals to your callbacks, or stick with your current solution. I know it's not ideal to create a monkey patch, but in this case, it might be the way to go.

Thanks.

**Comment by dilkhush** [comment]
There can be used valid? method to check for validations but here I am talking about the callbacks that are taking lots of time and doing dirty checking for all my callbacks also effect on application performance and code cleanness.
So my idea is that we don't need to trigger callbacks after sign_in and sign_out but we can validate through valid? method.
If to some usecase we require a callback after sign_in and sign_out, devise gem can provide a custom callback for model also like we have for controller after_signin_path_for etc. This way it will not call model's all *_update, *_save callbacks.

What do you think about this ?

**Comment by tegon** [comment]
@dilkhush I understand your situation, but it doesn't seem like Devise's responsibility to handle this - especially calling `#valid?` inside `Trackable` instead of a regular, `#save` - because it looks like this is something closely related to your application.
Also, since we already run the callbacks here, other people might already be relying on this behavior, which may cause other problems too.
