### ISSUE TITLE
sign_in does not work with timeoutable

### ISSUE THREAD

**Issue by stevecrozz** [plataformatec/devise#4773]
## Environment

- Ruby ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
- Rails 5.0.1
- Devise 4.2.0

## Current behavior

Using a custom authentication strategy in my app, I wind up calling `sign_in :user, user` when I'm ready to sign in a user. If that user arrived with an expired session, I get hit with https://github.com/plataformatec/devise/blob/v4.4.1/lib/devise/hooks/timeoutable.rb#L28. After some time, I found that Devise's own session controller works around this problem and disables timeoutable in order to do its work: https://github.com/plataformatec/devise/blob/v4.4.1/app/controllers/devise/sessions_controller.rb#L7

## Expected behavior

I think ideally, Devise would take care of not executing the timeoutable hook when calling sign_in because when you're signing a user in, it doesn't make sense to check to see if his old session has timed out.

If the current behavior is the desired behavior, I believe we at least need a note in the documentation for sign_in with a disclaimer about how this requires disabling timeoutable using the approach found in Devise's session_controller.

**Comment by tegon** [comment]
Hello @stevecrozz, thanks for your report.

We could do what you said - assume that an authentication always need to ignore the timeout - but since this is going to change devise's behavior significantly, that would require a major version, and we don't know if there's any code out there relying on the current behavior.
As far as I understand, you can get around this by setting `env["devise.skip_timeout"] = true` in your strategy, right?
If so, I guess is the way to go.

Thanks!

**Comment by stevecrozz** [comment]
Exactly. A note in the documentation to this effect would be welcome. Maybe it can be improved v5.

**Comment by tegon** [comment]
I'm not sure where is the best place to write this note though. Where do you think it will be more useful? On the `sign_in` method definition, or maybe in a Wiki page?
