### ISSUE TITLE
Model's validations are called on EVERY user's request

### ISSUE THREAD

**Issue by dhiemstra** [plataformatec/devise#4790]
https://github.com/plataformatec/devise/pull/4674 made a breaking change to the `update_tracked_fields!` method by removing `validate: false` from the `save()` call.

Basically this results in all the validations being called on every requested. Some companies run extended validations to ensure the validity of the email, phone number or vat number and often a 3rd party service / api is used to check this.

For us this meant an unexpected bill from Mailgun of more than $3500 because a massive amount of request were done in the last month to their validations API.

When looking at the original issue why this change was introduced I also don't think this is the proper fix. Why is `update_tracked_fields!` (with bang) even called when the user doesn't exist in the database? And, why is it even attempting to update tracked fields for a `new_user?`.

I suggest adding back the `validate: false` asap and fixing the original issue otherwise.

**Comment by tegon** [comment]
When we merged #4674, we didn't know that it would change the contract of `Trackable` that much, that was definitely a mistake, so I'm sorry for this.
I'll work on another solution for the problem since it's causing that much trouble. I haven't before because the other issues (#4742 for example) could be solved it by making small changes in the validations. But you have a valid point: it seems weird that we're calling the `update_tracked_fields!` on a record that isn't persisted yet.

I'd advise that those calls to external services would better be done in places where you can control how and when they're going to be executed, especially if you're paying for each request. Model validations can be called in many situations we aren't aware of and cause surprises such as this one.

Anyway, I'm definitely going to work on another way of doing this, so please downgrade for now.

Thanks for your report and sorry again for the trouble.
