### ISSUE TITLE
Punycode support

### ISSUE THREAD

**Issue by 23tux** [plataformatec/devise#4802]
## Environment

- Ruby **2.4.3**
- Rails **5.1**
- Devise **4.3**

## Current behavior

We have users that are using domains with special characters, for example user@exämple.de (german umlaut). We store them as unicode values in our database. This works for example in the current Firefox version, because they send them as the user enters them.

However, Chrome and Internet Explorer send the domain part as punycode, so user@exämple.de becomes user@xn--exmple-cua.de. When this happens devise tries to find the user but doesn't find one, because it is stored as unicode in the DB. Login fails.

## Expected behavior

The format should be configurable if you want to store a email as unicode or as punycode. It should make no difference in which format the browser or the user sends his credentials.

I'm not sure if there is a hook to achieve this, or if this is a missing feature. If it is, I will try a PR.

## Current workaround

We manipulate the `request.params` directly. That's not good, but so far the only option I see.

```
  prepend_before_action :convert_punycode_params
  private def convert_punycode_params
    return unless email = request.params.dig(:user, :email)
    # using https://github.com/mmriis/simpleidn for the conversion
    request.params[:user][:email] = email.split("@").map { |val| SimpleIDN.to_unicode(val) }.join("@")
  end
```

**Comment by tegon** [comment]
Hi @23tux, thanks for your report.

I think your solution is the way to go. Maybe you can also override the parameters instead of prepending a before action, but I think this is the path to follow.
The reason I say this is because this is a very specific use case and we can't do this with pure Ruby, we have to add a dependency to the `simpleidn` gem - which would be included for all the users, even for locales that don't need it.

Thanks!
