### ISSUE TITLE
devise/confirmations/new view displays error on visitor access

### ISSUE THREAD

**Issue by janosrusiczki** [plataformatec/devise#4805]
## Environment

- Ruby 2.3.1
- Rails 4.2.8
- Devise 3.5.10

## Current behavior

When loading the [generated devise/confirmations/new](https://github.com/plataformatec/devise/blob/master/app/views/devise/confirmations/new.html.erb) view as a visitor (not logged in user) the following error is displayed:

`Confirmation token can't be blank`

Also it does a select on users:

`User Load (2.5ms)  SELECT  `users`.* FROM `users` WHERE `users`.`confirmation_token` = ''  ORDER BY `users`.`id` ASC LIMIT 1`

After I submit the form the error disappears and only the correct error is displayed (Email not found, already confirmed, etc). Also the page's functionality is not affected: after I enter an unconfirmed email, the confirmation email is resent.

## Expected behavior

Error shouldn't be displayed on initial page load. Am I doing something wrong?

**Comment by tegon** [comment]
Hello @janosrusiczki, I've just tested here with the latest version and haven't got any errors.

Aren't you hitting the `POST` route?

**Comment by janosrusiczki** [comment]
No, I'm doing GET. Additionally if you google for `"Confirmation token can't be blank"` you'll see that there are many sites with the same problem:

* https://www.cprverify.org/users/confirmation
* https://www.dukop.dk/user/confirmation?locale=en
* https://www.schoolchapters.com/users/confirmation

This is not a page someone would frequently check, I suppose this problem appeared in a Devise upgrade and people didn't necessarily notice on a large scale.

**Comment by tegon** [comment]
Oh, I see. So you aren't hitting `confirmations/new`, but `confirmations/show`. I tested with `/users/confirmation/new` and the error doesn't happen.
This route is supposed to be used to [confirm an email](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/confirmations_controller.rb#L23), so the token has to be present. It works with `GET` because it's used as a link in emails.
So I'm not sure how we could handle this differently.

**Comment by janosrusiczki** [comment]
For me this solves the issue, thank you.
