### ISSUE TITLE
Cannot find auto-generated secret_key_base in development

### ISSUE THREAD

**Issue by ttilberg** [plataformatec/devise#4864]
A friend and I started a new project on Ruby 2.5.1, Rails 5.2.0, Devise 4.4.3

When I cloned the project, I was unable to run any rails/rake tasks, since Devise was not able to find the key.

The intent is that Rails will automatically set `SECRET_KEY_BASE` for you in dev and test: [link to merge](https://github.com/rails/rails/pull/30067/files#diff-580e183141be706162224ef696bdb6c7R413)

I see that [activity](
https://github.com/plataformatec/devise/pull/4712) has been made in the past few months around hunting down the `SECRET_KEY_BASE` but it seems that there is still a small bit more to go:

Currently Devise's [Secret Key Finder](https://github.com/plataformatec/devise/blob/master/lib/devise/secret_key_finder.rb) is unable to find the autogenerated key. Rails only does "auto generation" of the key in `Rails.application.secret_key_base` which is not currently checked.

@jcoyne mentioned this in https://github.com/plataformatec/devise/issues/4710#issuecomment-347624819 but it seems that the current implementation doesn't take into account `Rails.application.secret_key_base` -- the only autogenerated version in dev/test for Rails 5.2

```
[7] pry(main)> Rails.application.credentials.secret_key_base
=> nil
[8] pry(main)> Rails.application.secrets.secret_key_base
=> nil
[9] pry(main)> Rails.application.config.secret_key_base
=> nil
[10] pry(main)> Rails.application.secret_key_base
=> "d56814a3585e59378bbcabc1467d2693"
```

- [Rails.application.secret_key_base - not checked in devise](https://github.com/rails/rails/blob/master/railties/lib/rails/application.rb#L428)

The [help message for this error mentions to hardcode a secret key string into the initializer](https://github.com/plataformatec/devise/blob/f220b992c338122226f6fd396056d5a1adf28df8/lib/generators/templates/devise.rb#L11), which would affect all environments. For anyone who comes across this issue until this is better handled, a more appropriate option is to use

```ruby
  config.secret_key = Rails.application.secret_key_base
```

**Comment by tegon** [comment]
Hello @ttilberg, thanks for your report.

Seems like we didn't take this one into account when we created `Devise::SecretKeyFinder`. We should support it too. If you're willing to work on this, I'd be happy to accept a pull request.
Otherwise, I can do it, but it might take a while because I have some other issues to look into first.

Thanks!

**Comment by tegon** [comment]
@ttilberg can you test using the branch of #4869?

**Comment by kingdonb** [comment]
@ttilberg just curious where this behavior in development is documented?

I found the line of code that hashes the app name to generate secret_key_base for dev and test, but I was not able to find much about it in the documentation.

https://guides.rubyonrails.org/security.html#custom-credentials is the only canonical documentation about Encrypted Credentials that I could find at all, it's basically a footnote.  This is obviously not a devise issue, but I was wondering where you learned about `Rails.application.secret_key_base` – was it in #4710?

We are building our first Rails 5.2 app and only learned just now, when we've been getting prepared to go to production (with a staging environment) that our dev hosts are not using the encrypted credentials.  We probably should have known this, given we never provided them with a master key, but... still, seems like this should be documented somewhere prominently.

Rails 5.1 announcement from EngineYard at least came with some documentation about setting `config.read_encrypted_secrets = true` – I'm going to assume that since they're not called encrypted secrets anymore, that setting must no longer be relevant.

**Comment by ttilberg** [comment]
I can't remember exactly all the places I've seen it, but it is in the code comments for the method used:

https://github.com/rails/rails/blob/207588174e691221c5d50ba2f96d126471c9863b/railties/lib/rails/application.rb#L420

>>>
    # The secret_key_base is used as the input secret to the application's key generator, which in turn
    # is used to create all MessageVerifiers/MessageEncryptors, including the ones that sign and encrypt cookies.
    #
    # In test and development, this is simply derived as a MD5 hash of the application's name.
    #
    # In all other environments, we look for it first in ENV["SECRET_KEY_BASE"],
    # then credentials.secret_key_base, and finally secrets.secret_key_base. For most applications,
    # the correct place to store it is in the encrypted credentials file.
>>>

And also I recall reading it on various announcements, including the official release notes: https://guides.rubyonrails.org/5_2_release_notes.html#railties-notable-changes

This was a while back now, and I don't often work in Rails, so honestly I don't recall my exact chain of thoughts regarding this, but I did dive in pretty deep at the time. I do remember wondering about the problem your experiencing, but I don't recall if I ever settled on an appropriate resolution.
