### ISSUE TITLE
Devise does not use my custom confirmable.rb in project/lib/devise/models/confirmable.rb

### ISSUE THREAD

**Issue by bbtdev** [plataformatec/devise#4894]
Hello, I need to alter some methods in confirmable.rb, so I've copy pasted the content from confirmable.rb in my own project_name/lib/devise/models/confirmable.rb and added some Rails.logger lines to see if it's being used. It is not? How can I do this?

What I need is to use a value from the session variable inside the mailer. From what I see I need to modify confirmable.rb, is there a different way to do this?

**Comment by marcosanfilippo** [comment]
Can you post the config of devise in `routes.rb` ?

**Comment by tegon** [comment]
You have to make sure the file is being loaded correctly since `lib` is not always [autoloaded by default](https://til.hashrocket.com/posts/efb9003f8c-rails-autoload-paths).

Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. 

Thank you!
