### ISSUE TITLE
Wrong error message in devise/passwords/new

### ISSUE THREAD

**Issue by jacob-hedengren** [plataformatec/devise#4912]
Hi everyone! I'm using **Ruby 2.5.1**, **Rails 5.2.0** and **Devise 4.4.2**. 

**devise/passwords/new** seems to render wrong error message. When leaving email field blank and clicking on "Send me reset password instructions" this is the error messages being rendered:

**1 error prohibited this user from being saved:**

- Email can't be blank

Doesn't seem to make sense to me to say "...prohibited this user from being saved". I have been able to replicate this over and over again and the issue remains. 

Anyone else experiencing this? 

Thanks a lot in advance!

**Comment by tegon** [comment]
Hey @jacob-hedengren!

This can be bad UX, for sure, we know that we're trying to save the user object (with a reset password token) under the hood, but that doesn't make sense for the final user.
Either way, this message is coming from [Rails](https://github.com/rails/rails/blob/48c287d1963fba09cf620527d35519f67d5ca01a/guides/source/i18n.md#translations-for-the-active-record-error_messages_for-helper) when we call [`devise_error_messages!`](https://github.com/plataformatec/devise/blob/f39c6fd92774cb66f96f546d8d5e8281542b4e78/app/helpers/devise_helper.rb#L14). You can either override this method, or the i18n key, or even the `passwords/new` view itself, since this helper is used in most of Devise's views and it should work.
It's unlikely that we'd change this in Devise itself because it would break backward compatibility.

Thanks!

**Comment by jacob-hedengren** [comment]
Thanks a lot @tegon for clarifying this! I appreciate it!

**Comment by dogweather** [comment]
@jacob-hedengren would you accept a PR for a change to the `passwords/new` view? I'd like Devise to work "out of the box" as much as possible. But custom programming is required to fix this, and I don't believe it's mentioned in the docs as part of set up.
