### ISSUE TITLE
Undefined method "password" for User

### ISSUE THREAD

**Issue by elct9620** [plataformatec/devise#4913]
## Precheck

- Do not use the issues tracker for help or support, try Stack Overflow.
- For bugs, do a quick search and make sure the bug has not yet been reported
- Finally, be nice and have fun!

## Environment

- Ruby **2.5.1**
- Rails **5.2.0**
- Devise **4.4.3**

## Current behavior

1. Implement Omniauth only login feature
2. Disable `:database_authenticatable` feature

When I try to `save` user, it will show error `undefined method 'password' for #<User:0x00007ff448fd8ee8>`

## Expected behavior

It should work correctly even I didn't give `password`

## Note

I also try to use `password_required?` to disable password check, but it didn't apply.

**Comment by tegon** [comment]
Hey @elct9620, thanks for your report.

I have a couple of questions for you:

- Does your table have a `password` column?
- Are you using the `validatable` module?

**Comment by elct9620** [comment]
Hi, @tegon 

1. My table didn't have `password` column, the devise only add `encrypted_password` for me.
2. Yes, I enabled `validatable` module

---

I trace the `password` and `password=` in the source code, they are defined in `database_authenticatable` module, but I disable it.

I guess the reason I got this error is enabled `validatable` module, but if I override `password_required?` it should not call the `password` method.

**Comment by tegon** [comment]
Yeah, my bad, the column is `encrypted_password` indeed 😅 
My first thought was the `validatable` module too. Have you tried removing it completely to see if it works?

**Comment by elct9620** [comment]
When I remove `validatable` it can work well, but I still need it to validate email or other fields. So I choose to override `password_required?` to prevent it calling `password` inside `password_required?` method. But it didn't work for my project.

**Comment by tegon** [comment]
It's probably [this](https://github.com/plataformatec/devise/blob/master/lib/devise/models/validatable.rb#L42) validation then:
```ruby
validates_length_of :password, within: password_length, allow_blank: true
```
which does not call `password_required?` since it's allowed to be blank. In your case, it does not work because the `password` attribute was never defined (it's defined when `database_authenticable` is loaded). I think you can either:

- keep the `validatable` module and define an `attr_reader :password` for your model - which seems a little bit hacky;
- remove the `validatable` module and define the validations for `email` directly. They're actually pretty simple so I'd go with that option.

I'm going to close this because the `validatable` module is a group of common validations, which expect a resource that uses an `email`/`password` combination.

Thanks

**Comment by kicferk1** [comment]
I run into this issue as well. The project I'm working on is using password-less authentication (magic links and all), and I wanted to remove all links to passwords that we had. So I disabled `database_authenticatable`, I removed password fields from the database, and I got `undefined method 'password'`. 

@tegon do you think the line 
```
validates_length_of       :password, within: password_length, allow_blank: true
```
could be changed to
```
validates_length_of       :password, within: password_length, allow_blank: true, if: :password_required?
```
I don't understand the subtleties of this module and its goals, but it doesn't look like that change would violate any of the main principles. Happy to open a PR for it if you think it's a reasonable idea.

**Comment by tegon** [comment]
@kicferk1 I think there was a reason not to do this, but honestly I don't recall it now. I'm away from this project from a long time now, so I probably won't be able to help much.
But feel free to open a new issue with your proposal.
