### ISSUE TITLE
Model with optimistic locking (lock_version) and trackable devise module

### ISSUE THREAD

**Issue by asanghi** [plataformatec/devise#4930]
## Environment

- Ruby **2.3.3**
- Rails **4.2.10**
- Devise **3.5.0**

## Current behavior

My `Admin` model has optimistic locking switched on using Rails' `lock_version` column in the database. I also have `trackable` module switched on for this model. 
When admins login to the application, we trigger a number of ajax requests to the server and some of them fail randomly with `ActiveRecord::StaleObjectError: Attempted to update a stale object: Admin` error. We also use the `authenticate` helper in the `routes.rb` file. Previously I have tried to use `request.env['devise.skip_trackable'] = true` in the controllers as a prepended filter to avoid doing tracking on certain requests but the exception pesists.

The stacktraces indicate that the exception happens before the code hits the controller i.e. **during request routing** due to the use of `authenticate` helper. This happens randomly due to race conditions depending on when/how the requests for the same admin reach the server. Because the model has `lock_version` two requests at the same time will be unable to update the `admin` object at the same time. 

## Expected behavior

`update_tracked_fields!` should recover gracefully from the `ActiveRecord::StaleObjectError` error by either retrying or ignoring.

**Comment by tegon** [comment]
Hi @asanghi, I'm not sure devise should handle this. Locking strategy is very application-specific, and it seems strange that you're hitting trackable simultaneously multiple times for the same `Admin`. Would you mind to explain why this is happening?

**Comment by asanghi** [comment]
The UI fires multiple AJAX requests which hit the application at the same time. 
The requests hit the `authenticate` routing helper and because Admin model is `trackable`, multiple requests cause a race condition. This wouldnt be a problem unless your model also has optimistic locking turned on.

To answer your original question, it is because we have ajax requests originating from our dashboard.

**Comment by tegon** [comment]
@asanghi I see, then this looks like something very specific from your application. Something that would probably fix it is to first authenticate the user and only fire the dashboard requests after the user is authenticated.
I don't think we should handle locking in Devise because it would be hard to cover the possible cases - since the business rules changes from company to company.

**Comment by asanghi** [comment]
#4584 and this ticket have mixed similar concerns.

**Comment by tegon** [comment]
Hm, got it. I thought that you were sending requests to authenticate explicitly, but if it's because of what was mentioned in #4584 then I guess the best approach is to change that behavior. That way we won't call `trackable` every time and therefore you won't have lock issues.
I'm going to close this in favor of #4584 then. Thanks!
