### ISSUE TITLE
Storing encrypted reset_password_token

### ISSUE THREAD

**Issue by Edwardzyc** [plataformatec/devise#4932]
What are we mitigating against when we encrypt the reset_password_token?

It looks like we:

1. When user requests a password reset, we generate a hexdigest, store the hexdigest and return the raw to the user
2. Raw is sent as an email to the user
3. We get the raw again at update action, we run it through digest function and check it against the stored value

Is it possibly so that if someone gets read access(a dump) to the database that they can't reset other user passwords? (because if they had write access, they could just set the actual password to what they  wanted)

**Comment by colinross** [comment]
If an attacker has a un-filtered access to your database (or a dump!), you likely have a bigger problem then just a single user's credentials. That said...

I believe the rationale here is that since a valid reset_password_token could be used to reset the password, and in turn, be used to authenticate, it is encrypted.

This does add an additional layer of protection in a scenario where a (very) poorly written application exposes (i'm thinking some debugging code that made it to production) the user record.  In _that_ scenario, only hashes of credential-related data are shown, not the values needed for either the authenticate or password reset flow.

**Comment by tegon** [comment]
Yep, that's correct. Thanks, @colinross for looking at this!
