### ISSUE TITLE
Email regexp matches invalid email

### ISSUE THREAD

**Issue by prog1dev** [plataformatec/devise#4944]
## Environment

- Ruby **[2.3.0]**
- Rails **[4.2.0]**
- Devise **[master]**

## Current behavior

[`Devise.email_regexp`](https://github.com/plataformatec/devise/blob/master/lib/devise.rb#L116) matches invalid email `test@providercom`
```
[25] pry(main)> 'test@providercom'.match(Devise.email_regexp)
=> #<MatchData "test@providercom">
```

## Expected behavior

It does not match

**Comment by tegon** [comment]
Hi @prog1dev, thanks for reporting this.
I think we can include in the regex that the domain part should have a dot on it. We probably would need to include this in a major version though.
Are you willing to take a stab on this? If you are, let me know, otherwise, I'll leave it open for others to grab.

Thanks!

**Comment by CaiqueMitsuoka** [comment]
@tegon can I take this one? 😄

**Comment by tegon** [comment]
@CaiqueMitsuoka Sure thing, go ahead! 🚀

**Comment by CaiqueMitsuoka** [comment]
Hey
I did some digging into this problem, we I have a doubt, not sure which path to take.

So theoretically an email without the top level domain is valid. In the specification, the domain portion of the address need match the requirement for a hostname, which indeed would match `@providercom ` since it can be used as local domain like in ax intranet.

My question is if we would like to support this use case? If so, no patch is needed.

Some reading that I think can help:
[The discussion on the PR#4001 which is agreed to leave is as open as possible](https://github.com/plataformatec/devise/pull/4001)
Most of the discussion that I found point out to the [Wikipedia's Email address domain definition](https://en.wikipedia.org/wiki/Email_address#Domain) of which has [examples](https://en.wikipedia.org/wiki/Email_address#Examples).

cc @tegon @rafaelfranca

**Comment by tegon** [comment]
@CaiqueMitsuoka Thanks for digging into this, I didn't know about that.
After reading the discussion in the previous PR I think it's better to leave as it is today. As a library, it's better for Devise to be more general and leave the more restrict rules for the applications that want to add that behavior.

@prog1dev If you want to add this rule in your application, you can use the [email_regexp](https://github.com/plataformatec/devise/blob/master/lib/devise.rb#L115) configuration option.

Thanks!
