### ISSUE TITLE
Wiki page for "guest user" workaround has a "question" in it

### ISSUE THREAD

**Issue by hirokihokari** [plataformatec/devise#4952]
## Current behavior

Wiki page(https://github.com/plataformatec/devise/wiki/How-To:-Create-a-guest-user) has a question, rather than information or an instruction.
It's the paragraph that starts with "Wait a sec..."

## Expected behavior

Wiki should be a place of instruction/information, and not a discussion forum, correct?

**Comment by tegon** [comment]
Hello @hirokihokari, thanks for the issue.

The wiki is maintained by the community. It usually contains articles and instructions that worked for someone in the past, and they decided to share with the community - since it might be useful for other people too. That being said, we don't review any of the articles.
I agree with you that it would be better to not include questions in the Wiki. I guess the person that wrote did it hoping that someone would answer it. To ask questions, we usually prefer them to be posted in StackOverflow. 

I'm not sure what the intent of the code mentioned there (`manager.default_strategies(scope: :user).unshift :guest_user`) is, so I'm afraid I can't help much. If you have other questions, please create them in StackOverflow so that more people can help.


Thank you!
