### ISSUE TITLE
Wrong error message when logging in using changed, but unconfirmed email

### ISSUE THREAD

**Issue by kmehkeri** [plataformatec/devise#4956]
## Environment

- Ruby **2.4.2**
- Rails **5.0.4**
- Devise **4.3.0**

## Current behavior

I am using email as authentication key and confirmation enabled.

When a user updates his email, but has not confirmed it yet, an attempt to log in using new email yields "Invalid username or password" error.

## Expected behavior

As it is the case with registration, I would expect the error returned to be "You have to confirm your account before continuing".

**Comment by tegon** [comment]
This one is tricky because when the email is unconfirmed it's not yet saved in the `email` column, but in a separated column (`unconfirmed_email`) and the database authenticable strategy only tries to find the user based on the `email` column.
We could try to find a user based on both columns, but I don't think we should because it will have an impact in the query performance and also because that different message will allow email enumeration attacks (e.g. an attacker will now that a user exists in the system for that email).
I think as a library Devise should try to be more secure and fast by default. If that change makes sense for your application, you can create a custom Warden strategy that uses both columns to sign in the user.

Thanks!
