### ISSUE TITLE
active_for_authentication? raises TZInfo::AmbiguousTime error

### ISSUE THREAD

**Issue by roulili** [plataformatec/devise#4968]
Hi everyone!
I have noticed this strange behaviour today with devise's function "active_for_authentication?"
Which was raising an error: (TZInfo::AmbiguousTime) "1918-11-11 11:48:10 UTC is an ambiguous local time."
This happened today, at 11. (Im guessting there's too many eleens in th-oday's date).
however I can see that the date is incorrect to a century; so there might be something else amiss.

Or maybe it's a config in my server?

Anyway, I can't figure where this comes from, as the trace stops at this:

1918-11-11 11:48:10 UTC is an ambiguous local time.
app/models/user.rb:289:in `active_for_authentication?'

and active_for_authentication:
```
  def active_for_authentication?
    super && !self.blocked
  end
```

## Environment
Running in docker
- Ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-linux]
- Rails 4.2.5.1
- devise-3.4.1

Thanks in advance for looking into this!

**Comment by tegon** [comment]
Hey @roulili, thanks for the issue

It doesn't seem like this is a Devise issue. I did some research and found two issues: one in [tzinfo-data](https://github.com/tzinfo/tzinfo-data/issues/1) and other in [rails](https://github.com/rails/rails/pull/10826).
Since you're using an older version of Rails, upgrading might solve the issue.

Thanks!
