### ISSUE TITLE
Devise::email_regexp doesn't match all valid adresses

### ISSUE THREAD

**Issue by jomo** [plataformatec/devise#4980]
## Environment

- Devise **4.5.0**

## Current behavior

`Devise::email_regexp` is currently defined as:

```regex
/\A[^@\s]+@[^@\s]+\z/
```

It's a common misconception that email addresses are trivial to parse with a regular expression. A complete regex that catches all invalid addresses is [probably longer than equivalent parser code](http://www.ex-parrot.com/~pdw/Mail-RFC822-Address.html). So catching all _invalid_ addresses can't be the goal of this regex, but allowing all _valid_ addresses certainly should be. It currently does not.

To give an extreme example, `"well \\\" @ hi"@z` is a valid email address, but fails the regex test.

## Expected behavior

`Devise::email_regexp` should not fail on any given valid address. I suggest something like this:
```regex
/\A[\s\S]+@[\.\w]+\z/
```

**Comment by tegon** [comment]
Hi @jomo, thanks for the issue.

Indeed, a regex for email validation is not an easy thing to achieve. We had previous [discussions](https://github.com/plataformatec/devise/issues/4944) about the topic and we [think](https://github.com/plataformatec/devise/pull/4001) the current solution is a good enough default for most applications. That's why we expose the configuration option so that users are able to override the default with a regular expression that is better suitable for them.

Thanks!

**Comment by rafaelfranca** [comment]
The intention is not to change that regexp anymore.

**Comment by jomo** [comment]
Why?

**Comment by tegon** [comment]
Well, one of the reasons is that we would have to release a major version to change this default, since it's not backwards compatible.

Also, the example you sent (`"well \\\" @ hi"@z`) is not a common type of email, so I don't it's relevant for most applications. Do you have other examples of valid emails that are being rejected now?

**Comment by jomo** [comment]
I'd be fine with a backwards compatible default. Perhaps `"first last"@example.com` is a better example. Maybe not the most common address format, but do you only want to allow common addresses instead of standard conforming addresses by default?

**Comment by tegon** [comment]
> but do you only want to allow common addresses instead of standard conforming addresses by default?

Like you said in the beginning, the regular expression won't possibly cover all the cases. What I'm doing here is a tradeoff: is it worth it to make this change because of those not so common email addresses? Do most applications have this problem (real users couldn't register with those kind of emails)?
The way I see it, even though it's a valid email, most of the providers won't allow people to register with those addresses. I've tried in some of them and got validation errors:
<img width="797" alt="screen shot 2018-12-05 at 13 43 56" src="https://user-images.githubusercontent.com/3727827/49524948-de676880-f893-11e8-90c0-0d1eba3cc604.png">
<img width="482" alt="screen shot 2018-12-05 at 13 43 46" src="https://user-images.githubusercontent.com/3727827/49524954-e1625900-f893-11e8-951c-894451193e0b.png">
<img width="490" alt="screen shot 2018-12-05 at 13 43 35" src="https://user-images.githubusercontent.com/3727827/49524966-e58e7680-f893-11e8-967d-0fe156186346.png">
<img width="675" alt="screen shot 2018-12-05 at 13 43 20" src="https://user-images.githubusercontent.com/3727827/49524973-e8896700-f893-11e8-9864-973e0a4b80da.png">

**Comment by cseelus** [comment]
Currently it doesn't work with German Umlauts.

Mails like huber@gebäudereiniger.de (that are not uncommon here), should imho definitely work with Devise also.
