### ISSUE TITLE
Rails Template gives strange behavior with rails_command

### ISSUE THREAD

**Issue by kobaltz** [plataformatec/devise#4992]
## Environment

- Ruby 2.5.3
- Rails 5.2.2
- Devise 4.5.0

## Current behavior

When using the template feature of Rails, the following template gives some strange behavior.

```
gem 'devise'
run 'bundle install'

generate(:scaffold, 'user', 'name')
rails_command('generate devise:install')
rails_command('generate devise User')
```

This can be consumed with `rails new testapp -m template.rb` if you saved the file as template.rb

It is giving the following in the migration file

```
t.string :RAILS_ENV=development
```

However, when using the `generate` command instead of the `rails_command` like this below, it works as expected.

```
gem 'devise'
run 'bundle install'

generate(:scaffold, 'user', 'name')
generate('devise:install')
generate('devise','User')
```

## Expected behavior

I would expect the generator to properly create the migration files regardless of `rails_command` or `generate` being used when calling `rails g devise User`.

Thanks to [Simon Kiteley](https://www.driftingruby.com/users/simon-kiteley) finding this issue on Drifting Ruby

**Comment by tegon** [comment]
I tested here locally and it turns out this is not an issue with Devise. If you change the `scaffold` command to be used with `rails_command` you'll get the same issue:
```ruby
rails_command('generate scaffold User name')
```
```ruby
class CreateUsers < ActiveRecord::Migration[5.2]
  def change
    create_table :users do |t|
      t.string :name
      t.string :RAILS_ENV=development

      t.timestamps
    end
  end
end
```
This happens because `rails_command` [calls](https://github.com/rails/rails/blob/94b5cd3a20edadd6f6b8cf0bdf1a4d4919df86cb/railties/lib/rails/generators/actions.rb#L236) the `execute_command` method, which [appends](https://github.com/rails/rails/blob/94b5cd3a20edadd6f6b8cf0bdf1a4d4919df86cb/railties/lib/rails/generators/actions.rb#L301) the `RAILS_ENV=development` to the end of the command.

This end up generating the following commands:
```bash
"rails generate generate devise:install RAILS_ENV=development"
"rails generate scaffold User name RAILS_ENV=development"
```
The generator understands that as a new column.

I'm not even sure this is an issue with Rails itself, since the `generate` method - which [doesn't appends](https://github.com/rails/rails/blob/94b5cd3a20edadd6f6b8cf0bdf1a4d4919df86cb/railties/lib/rails/generators/actions.rb#L216) the environment to the end - seems to be meant to be used for generator, while `rails_command` seems to be meant for rake tasks and/or scripts. 

Maybe a note in the Rails documentation could make this more clear, something like "to run generators, please use the `#generate` method".

**Comment by kobaltz** [comment]
Thanks @tegon! Great catch.
