### ISSUE TITLE
Javascript POSTs to RegistrationsController#create no longer redirect to after_sign_up_path_for

### ISSUE THREAD

**Issue by philihp** [plataformatec/devise#5001]
## Pre-check

- [x] Do not use the issues tracker for help or support, try Stack Overflow.
- [x] For bugs, do a quick search and make sure the bug has not yet been reported
- [x] Finally, be nice and have fun!

## Environment

- Ruby 2.5.1
- Rails 5.1.1
- Devise 4.4.3 to 4.5.0

## Current behavior

In migrating to 4.5.0, I noticed that `after_sign_up_path_for` is now checking `is_navigational_format?` and if the request format is `:js` and it now returns nil, which changed in #4833. This can happen if a Rails form with `remote: true` tries to POST to [`Devise::RegistrationsController`](https://github.com/plataformatec/devise/blob/master/app/controllers/devise/registrations_controller.rb#L25) (which I imagine isn't uncommon?), however now when it hits the line

```ruby
respond_with resource, location: after_sign_up_path_for(resource)
```

`after_sign_up_path_for(resource)` returns nil, and the controller tries to respond with `user_url`.

## Expected behavior

Before, the registrations_controller would redirect. Is that no longer the case?

**Comment by tegon** [comment]
Hello @philihp, thanks for reporting this.

The reasoning behind #4833 was that `after_sign_up_path_for` was not doing the `is_navigational_format?` check while other similar methods were. 
While I think that makes sense, we didn't know the historic reasons behind that or if it would case any other issues.

But I think the problem here is that `:js` is not listed as a navigation format in Devise's [configuration](https://github.com/plataformatec/devise/blob/e3a00b27d19ba995891d7dd92394fe2900a789c2/lib/devise.rb#L220). Can you confirm if the following works?
```ruby
Devise.setup do |config|
  config.navigational_formats = ['*/*', :html, :js]
end
```

**Comment by philihp** [comment]
That works! Thank you. Is that the preferred solution? I'm seeing resources say that either adding to that list, or doing something described [here](https://stackoverflow.com/questions/16348724/devise-registrationupdate-via-js-in-rails) is ideal.

**Comment by tegon** [comment]
`respond_to` is another thing: it tells the controller to render that type of response. Adding `:js` to the this list makes the controllers perform redirects while without it they wouldn't.

I think it should be the better way to go. If you find other issues raised by this please let us know so that we can reopen the issue and look into it.

Thanks!
