### ISSUE TITLE
for more security: always return false on first login. is this a suitable strategy?

### ISSUE THREAD

**Issue by krtschmr** [plataformatec/devise#5008]
We recently had a discussion for securing a bitcoin platform. the idea was, that a user could activate a feature called _double login_. basically, if he logs in, regardless of correct or not, he always will get the message: _wrong user or password_. the second attempt, within _1 minute_ then will be valid and logs in the user (or redirects to 2FA page)

basically, this will help to protect against attackers who try to check big _mail:pass_ lists. if they get _authentication failed_, even tho it would have been valid, they will skip this one. only the user knows, he needs to login twice. 

does it make any sense or is this classic overthinking?

**Comment by tegon** [comment]
Hi @krtschmr, thanks for bringing this discussion here.

It seems a little overkill to me. This would create a bad experience for users in general which I think it shouldn't be encouraged as a library's default behaviour.

Also, I'm not sure it would be that effective, because if an attacker wants to get access to an account I suppose they would have some knowledge about the application - e.g they would realise this behaviour once they create an account.

That's why I'm going to close this issue. Thanks!
