### ISSUE TITLE
feature idea

### ISSUE THREAD

**Issue by natetech333** [plataformatec/devise#5056]
If a user has not confirmed there email address and they try to login, the system just redirects them to the sign in page. But I don't see a form or message that asks them to verify their email address. Should we add a feature that allows them to enter a verification code and prompts them for it if they keep trying to login into an unverified account?

**Comment by tegon** [comment]
Hi @natetech333, we do have that message already. What I suppose it might be happening in your case is that when a new Rails application is generated, by default the flash messages are not displayed in the page.
You have to manually include them, like this:
```erb
# app/views/layouts/application.html.erb

<!DOCTYPE html>
<html>
  <head>
    <title>ConfirmEmail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <% flash.each do |flash| %>
      <%= flash %>
    <% end %>
    <%= yield %>
  </body>
</html>
```
Then when you try to sign in the page will show the message:
<img width="1392" alt="Screen Shot 2019-04-05 at 10 41 18" src="https://user-images.githubusercontent.com/3727827/55632214-33f34980-5790-11e9-8be7-b2779123e5c9.png">

I've created a sample application to demonstrate this behavior.
[confirm-email.zip](https://github.com/plataformatec/devise/files/3048189/confirm-email.zip)

I'm going to close this issue since we already have the message. Thanks!
