### ISSUE TITLE
Issues /w Wiki Pages?

### ISSUE THREAD

**Issue by micodel** [plataformatec/devise#5068]
It seems there is something going on with the Wiki pages.

Many of them are blank and publicly editable.

These are pages that other resources reference and link to, so I assume they had content at one point.

**Comment by mracos** [comment]
Hi @micodel, thanks for the issue!

The wiki is maintained by the community. It usually contains articles and instructions that worked for someone in the past, and they decided to share with the community - since it might be useful for other people too. That being said, we don't review any of the articles.

The [wiki system keeps its history](https://help.github.com/en/articles/viewing-a-wikis-history-of-changes), so if you think that the content that was there before is still relevant please feel free to bring them back on.

Thanks again!
