### ISSUE TITLE
BLACKLIST_FOR_SERIALIZATION list should appear in the README file

### ISSUE THREAD

**Issue by FantasticJimmy** [plataformatec/devise#5108]
## Environment

- Ruby 2.5.3
- Rails 5.3
- Devise 4.5.0

## Current behavior

If devise is amounted along with a Modal say "User" , the devise will bring in additional helpers i.e. current_user which scan through the instance fields and serialize each of the field except for the BLACKLIST_FOR_SERIALIZATION in authenticatable.rb

A bug happens where Devise working along with ActsAsTaggableOn gem that bring in an instance helper "tag_list" on the User model which always gets serialize unless we concat "tag_list" to BLACKLIST_FOR_SERIALIZATION constant from the devise library. This is especially painful because calling tag_list will fire additional query against the DB (N+1), where in most cases that developers do not want to do. 

## Expected behavior
The README doc should state that BLACKLIST_FOR_SERIALIZATION is one of those config could be modified and leveraged.

**Comment by tegon** [comment]
Hi @FantasticJimmy, thanks for reporting this.

I don't think `BLACKLIST_FOR_SERIALIZATION` should be something encouraged to be modified. It's not a configuration option, but an internal constant to provide more secure defaults for Devise models. 

In order to exclude another field, I'd advise overriding ActiveModel's [`#serializable_hash`](https://api.rubyonrails.org/classes/ActiveModel/Serialization.html#method-i-serializable_hash), which should work since we're calling [`super`](https://github.com/plataformatec/devise/blob/master/lib/devise/models/authenticatable.rb#L115).

It seems like the ActsAsTaggableOn Gem could also override this method in order to exclude the method you mentioned since it fires another database query, but I do not have any context of that so I'm not sure it's a good option.

Anyway, I'm going to close this issue since constant is not encouraged to be modified.

Thanks again!
