### ISSUE TITLE
Unauthorized always by creating new session

### ISSUE THREAD

**Issue by devpolish** [plataformatec/devise#5123]
## Environment

- Ruby **2.5.1p57**
- Rails **5.2.1**
- Devise **4.4.3**

## Current behavior

I have an authentication model called Operator which has_many other different kind of operators.

```ruby
has_many :admins
has_many :hotel_operators
has_many :agency_operators
```

*Children associations only record additional information*

I'm trying to get logged into my account using my Operator authentication model with no result, all logging attempts are failed. I tried to use valid_password? method directly from the console, and it says that the password is valid, there is not any callback, it's a fresh Rails project.

<img width="1678" alt="Captura de pantalla 2019-08-20 a la(s) 3 23 02 p  m" src="https://user-images.githubusercontent.com/19675690/63381519-7348be00-c35e-11e9-8b0d-4808f74e6029.png">

<img width="1680" alt="Captura de pantalla 2019-08-20 a la(s) 3 23 54 p  m" src="https://user-images.githubusercontent.com/19675690/63381553-8b204200-c35e-11e9-8bbf-d6aa0eaa2a7d.png">

## Expected behavior

It's the first time after 5 years of using Devise that something like this happens, any clue?

**Comment by heavyperil** [comment]
@nardonykolyszyn Were you able to resolve this? I’m diagnosing what looks like a similar issue.

**Comment by nardonykolyszyn** [comment]
Sorry for answering at this time, this issue is not related with Devise but it's pretty common for other folks, if you're using SSL make sure you're setting headers properly, I was using Nginx so I had to fix:

`proxy_set_header X-Forwarded-Proto http` to

`proxy_set_header X-Forwarded-Proto $scheme`

In this way we handle requests automatically if it's HTTP or HTTPS (Or forced SSL)
